In [1]:
import os, sys

project_root = "/Users/beshoyarmanios/ncrna_platform"
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from models.features import build_feature_matrix
import pandas as pd

df = build_feature_matrix()
df.filter(regex="expr_").head()

✅ Feature matrix: 12 ncRNAs × 61 features

,expr_mean,expr_std,expr_median,expr_max,expr_nonzero_fraction,expr_cv,expr_log1p_mean,expr_log1p_max
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [2]:
import pandas as pd

expr = pd.read_csv("data/processed/expression_summary_features.csv")
expr.head()
expr.columns

Index(['symbol', 'expr_mean', 'expr_std', 'expr_median', 'expr_max',
       'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean',
       'expr_log1p_max'],
      dtype='object')

In [3]:
df.index, df.columns[:15]

(RangeIndex(start=0, stop=12, step=1),
 Index(['ncrna_id', 'symbol', 'biotype', 'conservation_score',
        'transcript_count', 'mean_abs_log2fc', 'mean_tau', 'n_sig_datasets',
        'n_datasets', 'mean_tpm_disease', 'n_up', 'n_down', 'de_consistency',
        'log_tpm_disease', 'sig_rate'],
       dtype='object'))

In [4]:
import pandas as pd

expr = pd.read_csv("data/processed/expression_summary_features.csv")

# 1) Current 'symbol' column is actually Ensembl
expr = expr.rename(columns={"symbol": "ensembl_id"})

expr.head()

,ensembl_id,expr_mean,expr_std,expr_median,expr_max,expr_nonzero_fraction,expr_cv,expr_log1p_mean,expr_log1p_max
0,ENSG00000000003,2535.210526,1043.461491,2422.0,5345,1.000000,0.411588,7.838426,8.584104
1,ENSG00000000005,3.456140,9.049606,0.0,58,0.438596,2.618414,1.494283,4.077537
2,ENSG00000000419,260.859649,102.360260,260.0,523,1.000000,0.392396,5.567809,6.261492
3,ENSG00000000457,203.245614,78.795685,205.0,454,1.000000,0.387687,5.319323,6.120297
4,ENSG00000000460,41.210526,20.740520,41.0,89,1.000000,0.503282,3.742670,4.499810

In [5]:
df["symbol"]

0     HNF1A-AS1
1         NEAT1
2        MALAT1
3        SNHG12
4          HULC
5        HOTAIR
6          GAS5
7     LINC01116
8          MIAT
9          XIST
10          H19
11         MEG3
Name: symbol, dtype: object

In [6]:
symbols = [
    "HNF1A-AS1", "NEAT1", "MALAT1", "SNHG12",
    "HULC", "HOTAIR", "GAS5", "LINC01116",
    "MIAT", "XIST", "H19", "MEG3",
]

mapping = pd.DataFrame({
    "symbol": symbols,
    "ensembl_id": [""] * len(symbols)  # fill these manually
})

mapping.to_csv("data/raw/ensembl_to_symbol_template.csv", index=False)
mapping

       symbol ensembl_id
0   HNF1A-AS1
1       NEAT1
2      MALAT1
3      SNHG12
4        HULC
5      HOTAIR
6        GAS5
7   LINC01116
8        MIAT
9        XIST
10        H19
11       MEG3

In [7]:
ann = pd.read_csv("data/raw/ensembl_to_symbol.csv")
ann

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/ensembl_to_symbol.csv'

In [8]:
ann = pd.read_csv("data/raw/ensembl_to_symbol.csv")
ann

       symbol       ensembl_id
0   HNF1A-AS1  ENSG00000241388
1       NEAT1  ENSG00000245532
2      MALAT1  ENSG00000251562
3      SNHG12  ENSG00000245910
4        HULC  ENSG00000251164
5      HOTAIR  ENSG00000228630
6        GAS5  ENSG00000234741
7   LINC01116  ENSG00000226549
8        MIAT  ENSG00000225783
9        XIST  ENSG00000229807
10        H19  ENSG00000130600
11       MEG3  ENSG00000214548

In [9]:
import pandas as pd

# Load expression summary
expr = pd.read_csv("data/processed/expression_summary_features.csv")

# At this point expr should have 'ensembl_id' as its ID column
# (you already renamed 'symbol' -> 'ensembl_id' earlier; if not, do it now)
# expr = expr.rename(columns={"symbol": "ensembl_id"})

# Load mapping
ann = pd.read_csv("data/raw/ensembl_to_symbol.csv")

# Attach symbols to expression features
expr_annot = expr.merge(ann, how="inner", on="ensembl_id")
expr_annot.head()

# Save annotated expression features
expr_annot.to_csv(
    "data/processed/expression_summary_features_annot.csv",
    index=False
)

KeyError: 'ensembl_id'

In [10]:
expr = pd.read_csv("data/processed/expression_summary_features.csv")
expr.columns

Index(['symbol', 'expr_mean', 'expr_std', 'expr_median', 'expr_max',
       'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean',
       'expr_log1p_max'],
      dtype='object')

In [11]:
expr = expr.rename(columns={"symbol": "ensembl_id"})
expr.columns

Index(['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max',
       'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean',
       'expr_log1p_max'],
      dtype='object')

In [12]:
ann = pd.read_csv("data/raw/ensembl_to_symbol.csv")

expr_annot = expr.merge(ann, how="inner", on="ensembl_id")
expr_annot.head()

expr_annot.to_csv(
    "data/processed/expression_summary_features_annot.csv",
    index=False
)

In [13]:
expr_annot[["symbol", "expr_mean", "expr_std"]].head(12)

Empty DataFrame
Columns: [symbol, expr_mean, expr_std]
Index: []

In [14]:
expr_annot[["symbol", "expr_mean", "expr_std"]].head(12)

Empty DataFrame
Columns: [symbol, expr_mean, expr_std]
Index: []

In [15]:
expr_annot.shape
expr_annot.head(12)

Empty DataFrame
Columns: [ensembl_id, expr_mean, expr_std, expr_median, expr_max, expr_nonzero_fraction, expr_cv, expr_log1p_mean, expr_log1p_max, symbol]
Index: []

In [16]:
expr_annot[["ensembl_id", "symbol", "expr_mean", "expr_std"]].head(12)

Empty DataFrame
Columns: [ensembl_id, symbol, expr_mean, expr_std]
Index: []

In [17]:
from models.features import build_feature_matrix
df = build_feature_matrix()
df[["symbol", "expr_mean", "expr_std", "expr_median"]]

✅ Feature matrix: 12 ncRNAs × 61 features

       symbol  expr_mean  expr_std  expr_median
0   HNF1A-AS1        0.0       0.0          0.0
1       NEAT1        0.0       0.0          0.0
2      MALAT1        0.0       0.0          0.0
3      SNHG12        0.0       0.0          0.0
4        HULC        0.0       0.0          0.0
5      HOTAIR        0.0       0.0          0.0
6        GAS5        0.0       0.0          0.0
7   LINC01116        0.0       0.0          0.0
8        MIAT        0.0       0.0          0.0
9        XIST        0.0       0.0          0.0
10        H19        0.0       0.0          0.0
11       MEG3        0.0       0.0          0.0

In [18]:
import pandas as pd

expr = pd.read_csv("data/processed/expression_summary_features.csv")
ann = pd.read_csv("data/raw/ensembl_to_symbol.csv")

# How many of the 12 Ensembl IDs appear in the expression summary?
ann["in_expr"] = ann["ensembl_id"].isin(expr["ensembl_id"])
ann

       symbol       ensembl_id  in_expr
0   HNF1A-AS1  ENSG00000241388    False
1       NEAT1  ENSG00000245532    False
2      MALAT1  ENSG00000251562    False
3      SNHG12  ENSG00000245910    False
4        HULC  ENSG00000251164    False
5      HOTAIR  ENSG00000228630    False
6        GAS5  ENSG00000234741    False
7   LINC01116  ENSG00000226549    False
8        MIAT  ENSG00000225783    False
9        XIST  ENSG00000229807    False
10        H19  ENSG00000130600    False
11       MEG3  ENSG00000214548    False

In [19]:
import pandas as pd

path = "data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv"
df = pd.read_csv(path, sep="\t")
print(df.shape)
print(df.columns[:10])
print(df.head())

(20531, 11070)
Index(['gene_id', 'TCGA-OR-A5J1-01A-11R-A29S-07',
       'TCGA-OR-A5J2-01A-11R-A29S-07', 'TCGA-OR-A5J3-01A-11R-A29S-07',
       'TCGA-OR-A5J5-01A-11R-A29S-07', 'TCGA-OR-A5J6-01A-31R-A29S-07',
       'TCGA-OR-A5J7-01A-11R-A29S-07', 'TCGA-OR-A5J8-01A-11R-A29S-07',
       'TCGA-OR-A5J9-01A-11R-A29S-07', 'TCGA-OR-A5JA-01A-11R-A29S-07'],
      dtype='object')
       gene_id  TCGA-OR-A5J1-01A-11R-A29S-07  TCGA-OR-A5J2-01A-11R-A29S-07  \
0  ?|100130426                        0.0000                        0.0000
1  ?|100133144                        3.2661                        2.6815
2  ?|100134869                        3.9385                        8.9948
3      ?|10357                      149.1350                       81.0777
4      ?|10431                     2034.1000                     1304.9300

   TCGA-OR-A5J3-01A-11R-A29S-07  TCGA-OR-A5J5-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        1.7301                        0.0000
2                        6.5650                        1.5492
3                       86.4879                       53.9117
4                     1054.6600                     2350.8900

   TCGA-OR-A5J6-01A-31R-A29S-07  TCGA-OR-A5J7-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        0.0000                        1.1673
2                        4.4709                        6.0529
3                       66.9063                      103.5060
4                     1257.9900                     1866.4300

   TCGA-OR-A5J8-01A-11R-A29S-07  TCGA-OR-A5J9-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        1.4422                        0.0000
2                        2.2876                        1.3599
3                       94.9316                       78.1955
4                      995.0270                     1762.1200

   TCGA-OR-A5JA-01A-11R-A29S-07  ...  TCGA-CG-4449-01A-01R-1157-13  \
0                        0.0000  ...                           NaN
1                        4.4556  ...                      4.358154
2                        5.0581  ...                      2.656360
3                       69.2389  ...                    633.299781
4                     1213.5300  ...                   1202.538277

   TCGA-CG-4462-01A-01R-1157-13  TCGA-CG-4465-01A-01R-1157-13  \
0                           NaN                           NaN
1                      5.676995                      5.219350
2                      3.342794                      2.423442
3                    294.018042                    686.569179
4                    644.002317                   1181.884532

   TCGA-CG-4466-01A-01R-1157-13  TCGA-CG-4469-01A-01R-1157-13  \
0                           NaN                           NaN
1                     14.846708                     20.115492
2                      5.055287                     11.626054
3                    563.573453                   1039.307597
4                    663.885074                    647.530395

   TCGA-CG-4472-01A-01R-1157-13  TCGA-CG-4474-01A-02R-1157-13  \
0                           NaN                           NaN
1                      6.997533                     18.311906
2                     13.654193                      7.417109
3                    639.238135                    742.479964
4                   1297.152549                   1152.909807

   TCGA-CG-4475-01A-01R-1157-13  TCGA-CG-4476-01A-01R-1157-13  \
0                           NaN                           NaN
1                     12.057112                     18.628740
2                     11.585177                     11.482418
3                    506.336449                    712.452165
4                   1375.495774                    971.893874

   TCGA-CG-4477-01A-01R-1157-13
0                           NaN
1                     17.874417
2                     14.919338
3                    703.713324
4                   1736.988111

[5 rows x 11070 columns]

In [20]:
import pandas as pd

path = "data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv"
df = pd.read_csv(path, sep="\t")
print(df.shape)
print(df.columns[:10])
print(df.head())

(20531, 11070)
Index(['gene_id', 'TCGA-OR-A5J1-01A-11R-A29S-07',
       'TCGA-OR-A5J2-01A-11R-A29S-07', 'TCGA-OR-A5J3-01A-11R-A29S-07',
       'TCGA-OR-A5J5-01A-11R-A29S-07', 'TCGA-OR-A5J6-01A-31R-A29S-07',
       'TCGA-OR-A5J7-01A-11R-A29S-07', 'TCGA-OR-A5J8-01A-11R-A29S-07',
       'TCGA-OR-A5J9-01A-11R-A29S-07', 'TCGA-OR-A5JA-01A-11R-A29S-07'],
      dtype='object')
       gene_id  TCGA-OR-A5J1-01A-11R-A29S-07  TCGA-OR-A5J2-01A-11R-A29S-07  \
0  ?|100130426                        0.0000                        0.0000
1  ?|100133144                        3.2661                        2.6815
2  ?|100134869                        3.9385                        8.9948
3      ?|10357                      149.1350                       81.0777
4      ?|10431                     2034.1000                     1304.9300

   TCGA-OR-A5J3-01A-11R-A29S-07  TCGA-OR-A5J5-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        1.7301                        0.0000
2                        6.5650                        1.5492
3                       86.4879                       53.9117
4                     1054.6600                     2350.8900

   TCGA-OR-A5J6-01A-31R-A29S-07  TCGA-OR-A5J7-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        0.0000                        1.1673
2                        4.4709                        6.0529
3                       66.9063                      103.5060
4                     1257.9900                     1866.4300

   TCGA-OR-A5J8-01A-11R-A29S-07  TCGA-OR-A5J9-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        1.4422                        0.0000
2                        2.2876                        1.3599
3                       94.9316                       78.1955
4                      995.0270                     1762.1200

   TCGA-OR-A5JA-01A-11R-A29S-07  ...  TCGA-CG-4449-01A-01R-1157-13  \
0                        0.0000  ...                           NaN
1                        4.4556  ...                      4.358154
2                        5.0581  ...                      2.656360
3                       69.2389  ...                    633.299781
4                     1213.5300  ...                   1202.538277

   TCGA-CG-4462-01A-01R-1157-13  TCGA-CG-4465-01A-01R-1157-13  \
0                           NaN                           NaN
1                      5.676995                      5.219350
2                      3.342794                      2.423442
3                    294.018042                    686.569179
4                    644.002317                   1181.884532

   TCGA-CG-4466-01A-01R-1157-13  TCGA-CG-4469-01A-01R-1157-13  \
0                           NaN                           NaN
1                     14.846708                     20.115492
2                      5.055287                     11.626054
3                    563.573453                   1039.307597
4                    663.885074                    647.530395

   TCGA-CG-4472-01A-01R-1157-13  TCGA-CG-4474-01A-02R-1157-13  \
0                           NaN                           NaN
1                      6.997533                     18.311906
2                     13.654193                      7.417109
3                    639.238135                    742.479964
4                   1297.152549                   1152.909807

   TCGA-CG-4475-01A-01R-1157-13  TCGA-CG-4476-01A-01R-1157-13  \
0                           NaN                           NaN
1                     12.057112                     18.628740
2                     11.585177                     11.482418
3                    506.336449                    712.452165
4                   1375.495774                    971.893874

   TCGA-CG-4477-01A-01R-1157-13
0                           NaN
1                     17.874417
2                     14.919338
3                    703.713324
4                   1736.988111

[5 rows x 11070 columns]

In [ ]:
import pandas as pd
import numpy as np

path = "data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv"

target_lncrnas = [
    "HNF1A-AS1", "NEAT1", "MALAT1", "SNHG12", "HULC", "HOTAIR",
    "GAS5", "LINC01116", "MIAT", "XIST", "H19", "MEG3"
]

df = pd.read_csv(path, sep="\t")

gene_col = df.columns[0]
df = df.rename(columns={gene_col: "gene_symbol"})

df["gene_symbol"] = df["gene_symbol"].astype(str).str.strip()

expr = df[df["gene_symbol"].isin(target_lncrnas)].copy()

sample_cols = [c for c in expr.columns if c != "gene_symbol"]
expr[sample_cols] = expr[sample_cols].apply(pd.to_numeric, errors="coerce")

summary = pd.DataFrame({
    "gene_symbol": expr["gene_symbol"],
    "expr_mean_tcga_pancan": expr[sample_cols].mean(axis=1),
    "expr_median_tcga_pancan": expr[sample_cols].median(axis=1),
    "expr_std_tcga_pancan": expr[sample_cols].std(axis=1),
    "expr_min_tcga_pancan": expr[sample_cols].min(axis=1),
    "expr_max_tcga_pancan": expr[sample_cols].max(axis=1),
    "expr_q1_tcga_pancan": expr[sample_cols].quantile(0.25, axis=1),
    "expr_q3_tcga_pancan": expr[sample_cols].quantile(0.75, axis=1),
})

summary["expr_iqr_tcga_pancan"] = (
    summary["expr_q3_tcga_pancan"] - summary["expr_q1_tcga_pancan"]
)

summary["expr_prevalence_tcga_pancan"] = (
    (expr[sample_cols] > 0).sum(axis=1) / len(sample_cols)
)

summary["in_tcga_pancan_expr"] = True

summary = summary.drop_duplicates(subset=["gene_symbol"]).reset_index(drop=True)

summary.to_csv(
    "data/processed/tcga_pancan_expression_summary_features.csv",
    index=False
)

print(summary)

In [ ]:
base = pd.read_csv("data/processed/expression_summary_features.csv")
tcga = pd.read_csv("data/processed/tcga_pancan_expression_summary_features.csv")

merged = base.merge(tcga, on="gene_symbol", how="left")

for col in [
    "expr_mean_tcga_pancan",
    "expr_median_tcga_pancan",
    "expr_std_tcga_pancan",
    "expr_min_tcga_pancan",
    "expr_max_tcga_pancan",
    "expr_q1_tcga_pancan",
    "expr_q3_tcga_pancan",
    "expr_iqr_tcga_pancan",
    "expr_prevalence_tcga_pancan",
]:
    merged[col] = merged[col].fillna(0.0)

merged["in_tcga_pancan_expr"] = merged["in_tcga_pancan_expr"].fillna(False)

merged.to_csv("data/processed/expression_summary_features_merged.csv", index=False)
print(merged.head())

In [ ]:
import pandas as pd

path = "data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv"
df = pd.read_csv(path, sep="\t")
print(df.shape)
print(df.columns[:10])
print(df.head())

In [1]:
import pandas as pd

path = "data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv"
df = pd.read_csv(path, sep="\t")
print(df.shape)
print(df.columns[:10])
print(df.head())

KeyboardInterrupt:

In [2]:
import pandas as pd

path = "data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv"
df = pd.read_csv(path, sep="\t")
print(df.shape)
print(df.columns[:10])
print(df.head())

(20531, 11070)
Index(['gene_id', 'TCGA-OR-A5J1-01A-11R-A29S-07',
       'TCGA-OR-A5J2-01A-11R-A29S-07', 'TCGA-OR-A5J3-01A-11R-A29S-07',
       'TCGA-OR-A5J5-01A-11R-A29S-07', 'TCGA-OR-A5J6-01A-31R-A29S-07',
       'TCGA-OR-A5J7-01A-11R-A29S-07', 'TCGA-OR-A5J8-01A-11R-A29S-07',
       'TCGA-OR-A5J9-01A-11R-A29S-07', 'TCGA-OR-A5JA-01A-11R-A29S-07'],
      dtype='object')
       gene_id  TCGA-OR-A5J1-01A-11R-A29S-07  TCGA-OR-A5J2-01A-11R-A29S-07  \
0  ?|100130426                        0.0000                        0.0000
1  ?|100133144                        3.2661                        2.6815
2  ?|100134869                        3.9385                        8.9948
3      ?|10357                      149.1350                       81.0777
4      ?|10431                     2034.1000                     1304.9300

   TCGA-OR-A5J3-01A-11R-A29S-07  TCGA-OR-A5J5-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        1.7301                        0.0000
2                        6.5650                        1.5492
3                       86.4879                       53.9117
4                     1054.6600                     2350.8900

   TCGA-OR-A5J6-01A-31R-A29S-07  TCGA-OR-A5J7-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        0.0000                        1.1673
2                        4.4709                        6.0529
3                       66.9063                      103.5060
4                     1257.9900                     1866.4300

   TCGA-OR-A5J8-01A-11R-A29S-07  TCGA-OR-A5J9-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        1.4422                        0.0000
2                        2.2876                        1.3599
3                       94.9316                       78.1955
4                      995.0270                     1762.1200

   TCGA-OR-A5JA-01A-11R-A29S-07  ...  TCGA-CG-4449-01A-01R-1157-13  \
0                        0.0000  ...                           NaN
1                        4.4556  ...                      4.358154
2                        5.0581  ...                      2.656360
3                       69.2389  ...                    633.299781
4                     1213.5300  ...                   1202.538277

   TCGA-CG-4462-01A-01R-1157-13  TCGA-CG-4465-01A-01R-1157-13  \
0                           NaN                           NaN
1                      5.676995                      5.219350
2                      3.342794                      2.423442
3                    294.018042                    686.569179
4                    644.002317                   1181.884532

   TCGA-CG-4466-01A-01R-1157-13  TCGA-CG-4469-01A-01R-1157-13  \
0                           NaN                           NaN
1                     14.846708                     20.115492
2                      5.055287                     11.626054
3                    563.573453                   1039.307597
4                    663.885074                    647.530395

   TCGA-CG-4472-01A-01R-1157-13  TCGA-CG-4474-01A-02R-1157-13  \
0                           NaN                           NaN
1                      6.997533                     18.311906
2                     13.654193                      7.417109
3                    639.238135                    742.479964
4                   1297.152549                   1152.909807

   TCGA-CG-4475-01A-01R-1157-13  TCGA-CG-4476-01A-01R-1157-13  \
0                           NaN                           NaN
1                     12.057112                     18.628740
2                     11.585177                     11.482418
3                    506.336449                    712.452165
4                   1375.495774                    971.893874

   TCGA-CG-4477-01A-01R-1157-13
0                           NaN
1                     17.874417
2                     14.919338
3                    703.713324
4                   1736.988111

[5 rows x 11070 columns]

In [3]:
import pandas as pd
import numpy as np

# Paths
expr_path = "data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv"
map_path = "data/raw/ensembl_to_symbol.csv"  # adjust if it's under data/reference/

# Load expression matrix
expr = pd.read_csv(expr_path, sep="\t")

print(expr.shape)
print(expr.columns[:10])
print(expr.head())

(20531, 11070)
Index(['gene_id', 'TCGA-OR-A5J1-01A-11R-A29S-07',
       'TCGA-OR-A5J2-01A-11R-A29S-07', 'TCGA-OR-A5J3-01A-11R-A29S-07',
       'TCGA-OR-A5J5-01A-11R-A29S-07', 'TCGA-OR-A5J6-01A-31R-A29S-07',
       'TCGA-OR-A5J7-01A-11R-A29S-07', 'TCGA-OR-A5J8-01A-11R-A29S-07',
       'TCGA-OR-A5J9-01A-11R-A29S-07', 'TCGA-OR-A5JA-01A-11R-A29S-07'],
      dtype='object')
       gene_id  TCGA-OR-A5J1-01A-11R-A29S-07  TCGA-OR-A5J2-01A-11R-A29S-07  \
0  ?|100130426                        0.0000                        0.0000
1  ?|100133144                        3.2661                        2.6815
2  ?|100134869                        3.9385                        8.9948
3      ?|10357                      149.1350                       81.0777
4      ?|10431                     2034.1000                     1304.9300

   TCGA-OR-A5J3-01A-11R-A29S-07  TCGA-OR-A5J5-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        1.7301                        0.0000
2                        6.5650                        1.5492
3                       86.4879                       53.9117
4                     1054.6600                     2350.8900

   TCGA-OR-A5J6-01A-31R-A29S-07  TCGA-OR-A5J7-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        0.0000                        1.1673
2                        4.4709                        6.0529
3                       66.9063                      103.5060
4                     1257.9900                     1866.4300

   TCGA-OR-A5J8-01A-11R-A29S-07  TCGA-OR-A5J9-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        1.4422                        0.0000
2                        2.2876                        1.3599
3                       94.9316                       78.1955
4                      995.0270                     1762.1200

   TCGA-OR-A5JA-01A-11R-A29S-07  ...  TCGA-CG-4449-01A-01R-1157-13  \
0                        0.0000  ...                           NaN
1                        4.4556  ...                      4.358154
2                        5.0581  ...                      2.656360
3                       69.2389  ...                    633.299781
4                     1213.5300  ...                   1202.538277

   TCGA-CG-4462-01A-01R-1157-13  TCGA-CG-4465-01A-01R-1157-13  \
0                           NaN                           NaN
1                      5.676995                      5.219350
2                      3.342794                      2.423442
3                    294.018042                    686.569179
4                    644.002317                   1181.884532

   TCGA-CG-4466-01A-01R-1157-13  TCGA-CG-4469-01A-01R-1157-13  \
0                           NaN                           NaN
1                     14.846708                     20.115492
2                      5.055287                     11.626054
3                    563.573453                   1039.307597
4                    663.885074                    647.530395

   TCGA-CG-4472-01A-01R-1157-13  TCGA-CG-4474-01A-02R-1157-13  \
0                           NaN                           NaN
1                      6.997533                     18.311906
2                     13.654193                      7.417109
3                    639.238135                    742.479964
4                   1297.152549                   1152.909807

   TCGA-CG-4475-01A-01R-1157-13  TCGA-CG-4476-01A-01R-1157-13  \
0                           NaN                           NaN
1                     12.057112                     18.628740
2                     11.585177                     11.482418
3                    506.336449                    712.452165
4                   1375.495774                    971.893874

   TCGA-CG-4477-01A-01R-1157-13
0                           NaN
1                     17.874417
2                     14.919338
3                    703.713324
4                   1736.988111

[5 rows x 11070 columns]

In [4]:
# gene_id format examples: "?|100130426", "ENSG00000223972.5|100287102"
expr["gene_id"] = expr["gene_id"].astype(str).str.strip()

# Split on "|" into two parts
parts = expr["gene_id"].str.split("|", n=1, expand=True)
expr["ensembl_raw"] = parts[0]
expr["entrez_id"] = parts[1]

# Remove version suffix from Ensembl, e.g. ENSG00000223972.5 -> ENSG00000223972
expr["ensembl_id"] = expr["ensembl_raw"].str.replace(r"\.\d+$", "", regex=True)

# Anything with "?" has no Ensembl, so set to NaN
expr.loc[expr["ensembl_id"] == "?", "ensembl_id"] = np.nan

expr[["gene_id", "ensembl_raw", "ensembl_id", "entrez_id"]].head()

       gene_id ensembl_raw ensembl_id  entrez_id
0  ?|100130426           ?        NaN  100130426
1  ?|100133144           ?        NaN  100133144
2  ?|100134869           ?        NaN  100134869
3      ?|10357           ?        NaN      10357
4      ?|10431           ?        NaN      10431

In [ ]:
# After you’ve created ensembl_id as before

# Load mapping once
mapping = pd.read_csv("data/raw/ensembl_to_symbol.csv")
mapping["ensembl_gene_id"] = mapping["ensembl_gene_id"].astype(str).str.strip()
mapping["gene_symbol"] = mapping["gene_symbol"].astype(str).str.strip()

# Merge
expr_mapped = expr.merge(
    mapping,
    left_on="ensembl_id",
    right_on="ensembl_gene_id",
    how="left"
)

expr_mapped["gene_symbol"] = expr_mapped["gene_symbol"].fillna(expr_mapped["ensembl_id"])

target_lncrnas = [
    "HNF1A-AS1", "NEAT1", "MALAT1", "SNHG12", "HULC", "HOTAIR",
    "GAS5", "LINC01116", "MIAT", "XIST", "H19", "MEG3"
]

expr_mapped[expr_mapped["gene_symbol"].isin(target_lncrnas)][
    ["gene_id", "ensembl_id", "gene_symbol"]
]

In [6]:
# After you’ve created ensembl_id as before

# Load mapping once
mapping = pd.read_csv("data/raw/ensembl_to_symbol.csv")
mapping["ensembl_gene_id"] = mapping["ensembl_gene_id"].astype(str).str.strip()
mapping["gene_symbol"] = mapping["gene_symbol"].astype(str).str.strip()

# Merge
expr_mapped = expr.merge(
    mapping,
    left_on="ensembl_id",
    right_on="ensembl_gene_id",
    how="left"
)

expr_mapped["gene_symbol"] = expr_mapped["gene_symbol"].fillna(expr_mapped["ensembl_id"])

target_lncrnas = [
    "HNF1A-AS1", "NEAT1", "MALAT1", "SNHG12", "HULC", "HOTAIR",
    "GAS5", "LINC01116", "MIAT", "XIST", "H19", "MEG3"
]

expr_mapped[expr_mapped["gene_symbol"].isin(target_lncrnas)][
    ["gene_id", "ensembl_id", "gene_symbol"]
]

KeyError: 'ensembl_gene_id'

In [7]:
import pandas as pd

mapping = pd.read_csv("data/raw/ensembl_to_symbol.csv")
print(mapping.columns)
mapping.head()

Index(['symbol', 'ensembl_id'], dtype='object')

      symbol       ensembl_id
0  HNF1A-AS1  ENSG00000241388
1      NEAT1  ENSG00000245532
2     MALAT1  ENSG00000251562
3     SNHG12  ENSG00000245910
4       HULC  ENSG00000251164

In [8]:
import pandas as pd
import numpy as np

expr_path = "data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv"
map_path  = "data/raw/ensembl_to_symbol.csv"

# Load expression matrix
expr = pd.read_csv(expr_path, sep="\t")
expr["gene_id"] = expr["gene_id"].astype(str).str.strip()

# Split gene_id: "ENSG00000223972.5|100287102" or "?|100130426"
parts = expr["gene_id"].str.split("|", n=1, expand=True)
expr["ensembl_raw"] = parts[0]
expr["entrez_id"]   = parts[1]

# Drop Ensembl version suffix
expr["ensembl_id"] = expr["ensembl_raw"].str.replace(r"\.\d+$", "", regex=True)
expr.loc[expr["ensembl_id"] == "?", "ensembl_id"] = np.nan

# Load mapping
mapping = pd.read_csv(map_path)
mapping["ensembl_id"] = mapping["ensembl_id"].astype(str).str.strip()
mapping["symbol"]     = mapping["symbol"].astype(str).str.strip()

# Join: keep only rows for your 12 lncRNAs
expr_mapped = expr.merge(
    mapping,
    on="ensembl_id",   # expr.ensembl_id ↔ mapping.ensembl_id
    how="inner"
)

expr_mapped[["gene_id", "ensembl_id", "symbol"]].head()

Empty DataFrame
Columns: [gene_id, ensembl_id, symbol]
Index: []

In [9]:
import pandas as pd

target_lncrnas = [
    "HNF1A-AS1", "NEAT1", "MALAT1", "SNHG12", "HULC", "HOTAIR",
    "GAS5", "LINC01116", "MIAT", "XIST", "H19", "MEG3"
]

# expr_mapped is already in memory from your last cell
expr_lncr = expr_mapped[expr_mapped["symbol"].isin(target_lncrnas)].copy()

# Identify sample columns: everything except meta
meta_cols = ["gene_id", "ensembl_raw", "entrez_id", "ensembl_id", "symbol"]
sample_cols = [c for c in expr_lncr.columns if c not in meta_cols]

expr_lncr[sample_cols] = expr_lncr[sample_cols].apply(pd.to_numeric, errors="coerce")

summary = pd.DataFrame({"gene_symbol": expr_lncr["symbol"]})

summary["expr_mean_tcga_pancan"]   = expr_lncr[sample_cols].mean(axis=1)
summary["expr_median_tcga_pancan"] = expr_lncr[sample_cols].median(axis=1)
summary["expr_std_tcga_pancan"]    = expr_lncr[sample_cols].std(axis=1)
summary["expr_min_tcga_pancan"]    = expr_lncr[sample_cols].min(axis=1)
summary["expr_max_tcga_pancan"]    = expr_lncr[sample_cols].max(axis=1)
summary["expr_q1_tcga_pancan"]     = expr_lncr[sample_cols].quantile(0.25, axis=1)
summary["expr_q3_tcga_pancan"]     = expr_lncr[sample_cols].quantile(0.75, axis=1)
summary["expr_iqr_tcga_pancan"]    = (
    summary["expr_q3_tcga_pancan"] - summary["expr_q1_tcga_pancan"]
)

summary["expr_prevalence_tcga_pancan"] = (
    (expr_lncr[sample_cols] > 0).sum(axis=1) / len(sample_cols)
)

summary["in_tcga_pancan_expr"] = True

# Collapse in case of duplicates
summary = summary.groupby("gene_symbol", as_index=False).mean(numeric_only=True)

summary.to_csv(
    "data/processed/tcga_pancan_expression_summary_features.csv",
    index=False
)

summary

Empty DataFrame
Columns: [gene_symbol, expr_mean_tcga_pancan, expr_median_tcga_pancan, expr_std_tcga_pancan, expr_min_tcga_pancan, expr_max_tcga_pancan, expr_q1_tcga_pancan, expr_q3_tcga_pancan, expr_iqr_tcga_pancan, expr_prevalence_tcga_pancan, in_tcga_pancan_expr]
Index: []

In [10]:
import pandas as pd

target_lncrnas = [
    "HNF1A-AS1", "NEAT1", "MALAT1", "SNHG12", "HULC", "HOTAIR",
    "GAS5", "LINC01116", "MIAT", "XIST", "H19", "MEG3"
]

base = pd.read_csv("data/processed/expression_summary_features.csv")
tcga = pd.read_csv("data/processed/tcga_pancan_expression_summary_features.csv")

merged = base.merge(tcga, on="gene_symbol", how="left")

for col in [
    "expr_mean_tcga_pancan",
    "expr_median_tcga_pancan",
    "expr_std_tcga_pancan",
    "expr_min_tcga_pancan",
    "expr_max_tcga_pancan",
    "expr_q1_tcga_pancan",
    "expr_q3_tcga_pancan",
    "expr_iqr_tcga_pancan",
    "expr_prevalence_tcga_pancan",
]:
    if col in merged.columns:
        merged[col] = merged[col].fillna(0.0)

if "in_tcga_pancan_expr" in merged.columns:
    merged["in_tcga_pancan_expr"] = merged["in_tcga_pancan_expr"].fillna(False)

merged.to_csv("data/processed/expression_summary_features_merged.csv", index=False)

merged.loc[
    merged["gene_symbol"].isin(target_lncrnas),
    ["gene_symbol", "expr_mean_tcga_pancan", "expr_prevalence_tcga_pancan"]
]

KeyError: 'gene_symbol'

In [11]:
import pandas as pd

base = pd.read_csv("data/processed/expression_summary_features.csv")
print(base.columns)
base.head()

Index(['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max',
       'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean',
       'expr_log1p_max'],
      dtype='object')

,ensembl_id,expr_mean,expr_std,expr_median,expr_max,expr_nonzero_fraction,expr_cv,expr_log1p_mean,expr_log1p_max
0,ENSG00000000003,2535.210526,1043.461491,2422.0,5345,1.000000,0.411588,7.838426,8.584104
1,ENSG00000000005,3.456140,9.049606,0.0,58,0.438596,2.618414,1.494283,4.077537
2,ENSG00000000419,260.859649,102.360260,260.0,523,1.000000,0.392396,5.567809,6.261492
3,ENSG00000000457,203.245614,78.795685,205.0,454,1.000000,0.387687,5.319323,6.120297
4,ENSG00000000460,41.210526,20.740520,41.0,89,1.000000,0.503282,3.742670,4.499810

In [12]:
import pandas as pd
import numpy as np

expr_path = "data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv"
map_path  = "data/raw/ensembl_to_symbol.csv"

expr = pd.read_csv(expr_path, sep="\t")
expr["gene_id"] = expr["gene_id"].astype(str).str.strip()

parts = expr["gene_id"].str.split("|", n=1, expand=True)
expr["ensembl_raw"] = parts[0]
expr["entrez_id"]   = parts[1]

expr["ensembl_id"] = expr["ensembl_raw"].str.replace(r"\.\d+$", "", regex=True)
expr.loc[expr["ensembl_id"] == "?", "ensembl_id"] = np.nan

mapping = pd.read_csv(map_path)
mapping["ensembl_id"] = mapping["ensembl_id"].astype(str).str.strip()
mapping["symbol"]     = mapping["symbol"].astype(str).str.strip()

expr_mapped = expr.merge(mapping, on="ensembl_id", how="inner")

target_lncrnas = [
    "HNF1A-AS1", "NEAT1", "MALAT1", "SNHG12", "HULC", "HOTAIR",
    "GAS5", "LINC01116", "MIAT", "XIST", "H19", "MEG3"
]

expr_lncr = expr_mapped[expr_mapped["symbol"].isin(target_lncrnas)].copy()

meta_cols = ["gene_id", "ensembl_raw", "entrez_id", "ensembl_id", "symbol"]
sample_cols = [c for c in expr_lncr.columns if c not in meta_cols]

expr_lncr[sample_cols] = expr_lncr[sample_cols].apply(pd.to_numeric, errors="coerce")

summary = pd.DataFrame({
    "ensembl_id": expr_lncr["ensembl_id"],
    "gene_symbol": expr_lncr["symbol"],
})

summary["expr_mean_tcga_pancan"]   = expr_lncr[sample_cols].mean(axis=1)
summary["expr_median_tcga_pancan"] = expr_lncr[sample_cols].median(axis=1)
summary["expr_std_tcga_pancan"]    = expr_lncr[sample_cols].std(axis=1)
summary["expr_min_tcga_pancan"]    = expr_lncr[sample_cols].min(axis=1)
summary["expr_max_tcga_pancan"]    = expr_lncr[sample_cols].max(axis=1)
summary["expr_q1_tcga_pancan"]     = expr_lncr[sample_cols].quantile(0.25, axis=1)
summary["expr_q3_tcga_pancan"]     = expr_lncr[sample_cols].quantile(0.75, axis=1)
summary["expr_iqr_tcga_pancan"]    = (
    summary["expr_q3_tcga_pancan"] - summary["expr_q1_tcga_pancan"]
)
summary["expr_prevalence_tcga_pancan"] = (
    (expr_lncr[sample_cols] > 0).sum(axis=1) / len(sample_cols)
)
summary["in_tcga_pancan_expr"] = True

summary = summary.groupby(["ensembl_id", "gene_symbol"], as_index=False).mean(numeric_only=True)

summary.to_csv(
    "data/processed/tcga_pancan_expression_summary_features.csv",
    index=False
)

summary

Empty DataFrame
Columns: [ensembl_id, gene_symbol, expr_mean_tcga_pancan, expr_median_tcga_pancan, expr_std_tcga_pancan, expr_min_tcga_pancan, expr_max_tcga_pancan, expr_q1_tcga_pancan, expr_q3_tcga_pancan, expr_iqr_tcga_pancan, expr_prevalence_tcga_pancan, in_tcga_pancan_expr]
Index: []

In [13]:
import pandas as pd

target_lncrnas = [
    "HNF1A-AS1", "NEAT1", "MALAT1", "SNHG12", "HULC", "HOTAIR",
    "GAS5", "LINC01116", "MIAT", "XIST", "H19", "MEG3"
]

base = pd.read_csv("data/processed/expression_summary_features.csv")
tcga = pd.read_csv("data/processed/tcga_pancan_expression_summary_features.csv")

merged = base.merge(tcga, on="ensembl_id", how="left")

for col in [
    "expr_mean_tcga_pancan",
    "expr_median_tcga_pancan",
    "expr_std_tcga_pancan",
    "expr_min_tcga_pancan",
    "expr_max_tcga_pancan",
    "expr_q1_tcga_pancan",
    "expr_q3_tcga_pancan",
    "expr_iqr_tcga_pancan",
    "expr_prevalence_tcga_pancan",
]:
    if col in merged.columns:
        merged[col] = merged[col].fillna(0.0)

if "in_tcga_pancan_expr" in merged.columns:
    merged["in_tcga_pancan_expr"] = merged["in_tcga_pancan_expr"].fillna(False)

merged.to_csv("data/processed/expression_summary_features_merged.csv", index=False)

# Quick sanity check: are your 12 Ensembl IDs now non-zero?
mapping = pd.read_csv("data/raw/ensembl_to_symbol.csv")
lncr_ensembl = mapping[mapping["symbol"].isin(target_lncrnas)]["ensembl_id"].tolist()

merged[merged["ensembl_id"].isin(lncr_ensembl)][
    ["ensembl_id", "expr_mean_tcga_pancan", "expr_prevalence_tcga_pancan"]
]

/var/folders/wt/ddrmj3m50kl7lkymt7bn66j40000gn/T/ipykernel_6694/1587566212.py:25: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  merged[col] = merged[col].fillna(0.0)
/var/folders/wt/ddrmj3m50kl7lkymt7bn66j40000gn/T/ipykernel_6694/1587566212.py:28: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  merged["in_tcga_pancan_expr"] = merged["in_tcga_pancan_expr"].fillna(False)

Empty DataFrame
Columns: [ensembl_id, expr_mean_tcga_pancan, expr_prevalence_tcga_pancan]
Index: []

In [14]:
expr_summary = pd.read_csv(
    "data/processed/expression_summary_features_merged.csv"
)

In [15]:
from models.features import build_feature_matrix
df = build_feature_matrix()
df.filter(regex="expr_").head()

✅ Feature matrix: 12 ncRNAs × 53 features

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [16]:
import pandas as pd
from models.features import build_feature_matrix

df = build_feature_matrix()

# Show the first few rows with both old and new expression features
expr_cols = [c for c in df.columns if "expr_" in c]
df[expr_cols].head()

✅ Feature matrix: 12 ncRNAs × 53 features

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [17]:
import pandas as pd
from models.features import build_feature_matrix

df = build_feature_matrix()

expr_cols = [c for c in df.columns if "expr_" in c or "tcga" in c]
df[expr_cols].head()

✅ Feature matrix: 12 ncRNAs × 53 features

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [18]:
from models.features import build_feature_matrix
df = build_feature_matrix()

# 1) Just list the expression columns so we can see their names
[col for col in df.columns if "expr_" in col or "tcga" in col]

✅ Feature matrix: 12 ncRNAs × 53 features

[]

In [19]:
# 2) Use .loc with columns listed explicitly
expr_cols = [c for c in df.columns if "expr_" in c or "tcga" in c]
df.loc[:, expr_cols].head().to_string()

'Empty DataFrame\nColumns: []\nIndex: [0, 1, 2, 3, 4]'

In [20]:
import pandas as pd

expr_summary = pd.read_csv("data/processed/expression_summary_features_merged.csv")
expr_summary.columns

Index(['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max',
       'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean', 'expr_log1p_max',
       'gene_symbol', 'expr_mean_tcga_pancan', 'expr_median_tcga_pancan',
       'expr_std_tcga_pancan', 'expr_min_tcga_pancan', 'expr_max_tcga_pancan',
       'expr_q1_tcga_pancan', 'expr_q3_tcga_pancan', 'expr_iqr_tcga_pancan',
       'expr_prevalence_tcga_pancan', 'in_tcga_pancan_expr'],
      dtype='object')

In [21]:
%load_ext autoreload
%autoreload 2

from models.features import build_feature_matrix
df = build_feature_matrix()

[col for col in df.columns if "tcga_pancan" in col]

✅ Feature matrix: 12 ncRNAs × 53 features

[]

In [22]:
df[[c for c in df.columns if "tcga_pancan" in c]].head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [23]:
%load_ext autoreload
%autoreload 2

from models.features import _load_expression_summary_features, build_feature_matrix

expr_summary_df = _load_expression_summary_features()
print(expr_summary_df.columns.tolist())

df = build_feature_matrix()
print([c for c in df.columns if "tcga_pancan" in c])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max', 'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean', 'expr_log1p_max', 'symbol']
✅ Feature matrix: 12 ncRNAs × 53 features
[]

In [24]:
import pandas as pd

# 1) Base GEO expression summary
base = pd.read_csv("data/processed/expression_summary_features.csv")

# 2) TCGA PanCan summary with Ensembl and symbol + tcga columns
tcga = pd.read_csv("data/processed/tcga_pancan_expression_summary_features.csv")

print("Base columns:", base.columns.tolist())
print("TCGA columns:", tcga.columns.tolist())

# 3) Merge on ensembl_id
merged = base.merge(tcga, on="ensembl_id", how="left")

# If tcga file has gene_symbol, normalize the name
if "gene_symbol" in merged.columns and "symbol" not in merged.columns:
    merged = merged.rename(columns={"gene_symbol": "symbol"})

merged.to_csv("data/processed/expression_summary_features_merged.csv", index=False)

print("Merged columns:", merged.columns.tolist())

Base columns: ['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max', 'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean', 'expr_log1p_max']
TCGA columns: ['ensembl_id', 'gene_symbol', 'expr_mean_tcga_pancan', 'expr_median_tcga_pancan', 'expr_std_tcga_pancan', 'expr_min_tcga_pancan', 'expr_max_tcga_pancan', 'expr_q1_tcga_pancan', 'expr_q3_tcga_pancan', 'expr_iqr_tcga_pancan', 'expr_prevalence_tcga_pancan', 'in_tcga_pancan_expr']
Merged columns: ['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max', 'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean', 'expr_log1p_max', 'symbol', 'expr_mean_tcga_pancan', 'expr_median_tcga_pancan', 'expr_std_tcga_pancan', 'expr_min_tcga_pancan', 'expr_max_tcga_pancan', 'expr_q1_tcga_pancan', 'expr_q3_tcga_pancan', 'expr_iqr_tcga_pancan', 'expr_prevalence_tcga_pancan', 'in_tcga_pancan_expr']

In [25]:
%reload_ext autoreload

from models.features import _load_expression_summary_features, build_feature_matrix

expr_summary_df = _load_expression_summary_features()
print(expr_summary_df.columns.tolist())

['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max', 'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean', 'expr_log1p_max', 'symbol']

In [26]:
df[[c for c in df.columns if "tcga_pancan" in c]].head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [27]:
from models.features import EXPR_SUMMARY_PATH
import os

print("EXPR_SUMMARY_PATH:", EXPR_SUMMARY_PATH)
print("Exists:", os.path.exists(EXPR_SUMMARY_PATH))

# Inspect first few rows directly
import pandas as pd
raw = pd.read_csv(EXPR_SUMMARY_PATH)
print("Raw columns:", raw.columns.tolist())

EXPR_SUMMARY_PATH: /Users/beshoyarmanios/ncrna_platform/data/processed/expression_summary_features_annot.csv
Exists: True
Raw columns: ['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max', 'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean', 'expr_log1p_max', 'symbol']

In [28]:
%reload_ext autoreload

from models.features import EXPR_SUMMARY_PATH, _load_expression_summary_features, build_feature_matrix
import pandas as pd, os

print("EXPR_SUMMARY_PATH:", EXPR_SUMMARY_PATH)
print("Exists:", os.path.exists(EXPR_SUMMARY_PATH))

raw = pd.read_csv(EXPR_SUMMARY_PATH)
print("Raw columns:", raw.columns.tolist())

expr_summary_df = _load_expression_summary_features()
print("Helper columns:", expr_summary_df.columns.tolist())

EXPR_SUMMARY_PATH: /Users/beshoyarmanios/ncrna_platform/data/processed/expression_summary_features_annot.csv
Exists: True
Raw columns: ['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max', 'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean', 'expr_log1p_max', 'symbol', 'expr_mean_tcga_pancan', 'expr_median_tcga_pancan', 'expr_std_tcga_pancan', 'expr_min_tcga_pancan', 'expr_max_tcga_pancan', 'expr_q1_tcga_pancan', 'expr_q3_tcga_pancan', 'expr_iqr_tcga_pancan', 'expr_prevalence_tcga_pancan', 'in_tcga_pancan_expr']
Helper columns: ['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max', 'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean', 'expr_log1p_max', 'symbol', 'expr_mean_tcga_pancan', 'expr_median_tcga_pancan', 'expr_std_tcga_pancan', 'expr_min_tcga_pancan', 'expr_max_tcga_pancan', 'expr_q1_tcga_pancan', 'expr_q3_tcga_pancan', 'expr_iqr_tcga_pancan', 'expr_prevalence_tcga_pancan', 'in_tcga_pancan_expr']

In [29]:
master_q = """
    SELECT
        ncrna_id,
        ensembl_id,
        symbol,
        biotype,
        conservation_score,
        transcript_count
    FROM ncrna_master
"""

In [30]:
master_q = """
    SELECT
        ncrna_id,
        ensembl_id,
        symbol,
        biotype,
        conservation_score,
        transcript_count
    FROM ncrna_master
"""

In [31]:
expr_summary_df = _load_expression_summary_features()
if not expr_summary_df.empty:
    df["symbol"] = df["symbol"].astype(str).str.strip()
    expr_summary_df["symbol"] = expr_summary_df["symbol"].astype(str).str.strip()
    df = df.merge(expr_summary_df, on="symbol", how="left", suffixes=("", "_expr"))

    if "ensembl_id_expr" in df.columns:
        df = df.drop(columns=["ensembl_id_expr"])

In [32]:
%reload_ext autoreload

from models.features import build_feature_matrix
df = build_feature_matrix()

print([c for c in df.columns if "tcga_pancan" in c])
print(df[[c for c in df.columns if "tcga_pancan" in c]].head())

✅ Feature matrix: 12 ncRNAs × 72 features
['expr_mean_tcga_pancan', 'expr_median_tcga_pancan', 'expr_std_tcga_pancan', 'expr_min_tcga_pancan', 'expr_max_tcga_pancan', 'expr_q1_tcga_pancan', 'expr_q3_tcga_pancan', 'expr_iqr_tcga_pancan', 'expr_prevalence_tcga_pancan', 'in_tcga_pancan_expr']
   expr_mean_tcga_pancan  expr_median_tcga_pancan  expr_std_tcga_pancan  \
0                    0.0                      0.0                   0.0
1                    0.0                      0.0                   0.0
2                    0.0                      0.0                   0.0
3                    0.0                      0.0                   0.0
4                    0.0                      0.0                   0.0

   expr_min_tcga_pancan  expr_max_tcga_pancan  expr_q1_tcga_pancan  \
0                   0.0                   0.0                  0.0
1                   0.0                   0.0                  0.0
2                   0.0                   0.0                  0.0
3                   0.0                   0.0                  0.0
4                   0.0                   0.0                  0.0

   expr_q3_tcga_pancan  expr_iqr_tcga_pancan  expr_prevalence_tcga_pancan  \
0                  0.0                   0.0                          0.0
1                  0.0                   0.0                          0.0
2                  0.0                   0.0                          0.0
3                  0.0                   0.0                          0.0
4                  0.0                   0.0                          0.0

   in_tcga_pancan_expr
0                    0
1                    0
2                    0
3                    0
4                    0

In [33]:
from models.features import _load_expression_summary_features
import sqlite3
import pandas as pd

conn = sqlite3.connect("ncrna_platform.db")

master = pd.read_sql_query("""
    SELECT ncrna_id, ensembl_id, symbol
    FROM ncrna_master
""", conn)

conn.close()

expr = _load_expression_summary_features()[[
    "ensembl_id", "symbol", "in_tcga_pancan_expr"
]].copy()

master["ensembl_id"] = master["ensembl_id"].astype(str).str.strip()
expr["ensembl_id"] = expr["ensembl_id"].astype(str).str.strip()

master["ensembl_base"] = master["ensembl_id"].str.replace(r"\.\d+$", "", regex=True)
expr["ensembl_base"] = expr["ensembl_id"].str.replace(r"\.\d+$", "", regex=True)

print("Master ensembl_id:")
print(master[["ncrna_id", "symbol", "ensembl_id", "ensembl_base"]].head(20))

print("\nExpr ensembl_id:")
print(expr[["symbol", "ensembl_id", "ensembl_base", "in_tcga_pancan_expr"]].head(20))

exact_matches = master["ensembl_id"].isin(expr["ensembl_id"]).sum()
base_matches = master["ensembl_base"].isin(expr["ensembl_base"]).sum()

print("\nExact matches:", exact_matches)
print("Base matches:", base_matches)

diag = master.merge(
    expr[["ensembl_id", "ensembl_base", "symbol", "in_tcga_pancan_expr"]],
    on="ensembl_base",
    how="left",
    suffixes=("_master", "_expr")
)

print("\nDiagnostic merge:")
print(diag[[
    "ncrna_id", "symbol_master", "ensembl_id_master",
    "symbol_expr", "ensembl_id_expr", "in_tcga_pancan_expr"
]].head(20))

Master ensembl_id:
      ncrna_id     symbol       ensembl_id     ensembl_base
0   LNCRNA_001  HNF1A-AS1  ENSG00000197253  ENSG00000197253
1   LNCRNA_002      NEAT1  ENSG00000245532  ENSG00000245532
2   LNCRNA_003     MALAT1  ENSG00000251562  ENSG00000251562
3   LNCRNA_004     SNHG12  ENSG00000099834  ENSG00000099834
4   LNCRNA_005       HULC  ENSG00000251164  ENSG00000251164
5   LNCRNA_006     HOTAIR  ENSG00000228630  ENSG00000228630
6   LNCRNA_007       GAS5  ENSG00000234741  ENSG00000234741
7   LNCRNA_008  LINC01116  ENSG00000230876  ENSG00000230876
8   LNCRNA_009       MIAT  ENSG00000225783  ENSG00000225783
9   LNCRNA_010       XIST  ENSG00000229807  ENSG00000229807
10  LNCRNA_011        H19             None             None
11  LNCRNA_012       MEG3             None             None

Expr ensembl_id:
   symbol       ensembl_id     ensembl_base  in_tcga_pancan_expr
0     nan  ENSG00000000003  ENSG00000000003                  NaN
1     nan  ENSG00000000005  ENSG00000000005                  NaN
2     nan  ENSG00000000419  ENSG00000000419                  NaN
3     nan  ENSG00000000457  ENSG00000000457                  NaN
4     nan  ENSG00000000460  ENSG00000000460                  NaN
5     nan  ENSG00000000938  ENSG00000000938                  NaN
6     nan  ENSG00000000971  ENSG00000000971                  NaN
7     nan  ENSG00000001036  ENSG00000001036                  NaN
8     nan  ENSG00000001084  ENSG00000001084                  NaN
9     nan  ENSG00000001167  ENSG00000001167                  NaN
10    nan  ENSG00000001460  ENSG00000001460                  NaN
11    nan  ENSG00000001461  ENSG00000001461                  NaN
12    nan  ENSG00000001497  ENSG00000001497                  NaN
13    nan  ENSG00000001561  ENSG00000001561                  NaN
14    nan  ENSG00000001617  ENSG00000001617                  NaN
15    nan  ENSG00000001626  ENSG00000001626                  NaN
16    nan  ENSG00000001629  ENSG00000001629                  NaN
17    nan  ENSG00000001630  ENSG00000001630                  NaN
18    nan  ENSG00000001631  ENSG00000001631                  NaN
19    nan  ENSG00000002016  ENSG00000002016                  NaN

Exact matches: 2
Base matches: 2

Diagnostic merge:
      ncrna_id symbol_master ensembl_id_master symbol_expr  ensembl_id_expr  \
0   LNCRNA_001     HNF1A-AS1   ENSG00000197253         nan  ENSG00000197253
1   LNCRNA_002         NEAT1   ENSG00000245532         NaN              NaN
2   LNCRNA_003        MALAT1   ENSG00000251562         NaN              NaN
3   LNCRNA_004        SNHG12   ENSG00000099834         nan  ENSG00000099834
4   LNCRNA_005          HULC   ENSG00000251164         NaN              NaN
5   LNCRNA_006        HOTAIR   ENSG00000228630         NaN              NaN
6   LNCRNA_007          GAS5   ENSG00000234741         NaN              NaN
7   LNCRNA_008     LINC01116   ENSG00000230876         NaN              NaN
8   LNCRNA_009          MIAT   ENSG00000225783         NaN              NaN
9   LNCRNA_010          XIST   ENSG00000229807         NaN              NaN
10  LNCRNA_011           H19              None         NaN              NaN
11  LNCRNA_012          MEG3              None         NaN              NaN

    in_tcga_pancan_expr
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
5                   NaN
6                   NaN
7                   NaN
8                   NaN
9                   NaN
10                  NaN
11                  NaN

In [34]:
# After computing TCGA pancan stats into expr_summary_df
target_ids = [
    "ENSG00000197253",  # HNF1A-AS1
    "ENSG00000245532",  # NEAT1
    "ENSG00000251562",  # MALAT1
    "ENSG00000099834",  # SNHG12
    "ENSG00000251164",  # HULC
    "ENSG00000228630",  # HOTAIR
    "ENSG00000234741",  # GAS5
    "ENSG00000230876",  # LINC01116
    "ENSG00000225783",  # MIAT
    "ENSG00000229807",  # XIST
]

probe = expr_summary_df[
    expr_summary_df["ensembl_id"].isin(target_ids)
][[
    "ensembl_id", "expr_mean_tcga_pancan", "expr_prevalence_tcga_pancan",
    "in_tcga_pancan_expr"
]]
print("TCGA probe for ncRNAs:")
print(probe)

TCGA probe for ncRNAs:
            ensembl_id  expr_mean_tcga_pancan  expr_prevalence_tcga_pancan  \
2108   ENSG00000099834                    NaN                          NaN
16493  ENSG00000197253                    NaN                          NaN

       in_tcga_pancan_expr
2108                   NaN
16493                  NaN

In [35]:
import pandas as pd

tcga = pd.read_csv("data/processed/tcga_pancan_expression_summary_features.csv")
expr = pd.read_csv("data/processed/expression_summary_features.csv")

print("TCGA shape:", tcga.shape)
print("Expression summary shape:", expr.shape)
print("\nTCGA head:")
print(tcga.head())
print("\nTCGA non-null counts:")
print(tcga.notna().sum())

TCGA shape: (0, 12)
Expression summary shape: (19786, 9)

TCGA head:
Empty DataFrame
Columns: [ensembl_id, gene_symbol, expr_mean_tcga_pancan, expr_median_tcga_pancan, expr_std_tcga_pancan, expr_min_tcga_pancan, expr_max_tcga_pancan, expr_q1_tcga_pancan, expr_q3_tcga_pancan, expr_iqr_tcga_pancan, expr_prevalence_tcga_pancan, in_tcga_pancan_expr]
Index: []

TCGA non-null counts:
ensembl_id                     0
gene_symbol                    0
expr_mean_tcga_pancan          0
expr_median_tcga_pancan        0
expr_std_tcga_pancan           0
expr_min_tcga_pancan           0
expr_max_tcga_pancan           0
expr_q1_tcga_pancan            0
expr_q3_tcga_pancan            0
expr_iqr_tcga_pancan           0
expr_prevalence_tcga_pancan    0
in_tcga_pancan_expr            0
dtype: int64

In [36]:
import os

for root, dirs, files in os.walk("data"):
    for f in files:
        if "tcga" in f.lower() and ("expr" in f.lower() or "count" in f.lower()):
            print(os.path.join(root, f))

data/processed/tcga_pancan_expression_summary_features.csv
data/processed/.ipynb_checkpoints/tcga_pancan_expression_summary_features-checkpoint.csv

In [37]:
import os

for root, dirs, files in os.walk("."):
    for f in files:
        name = f.lower()
        if "tcga" in name:
            print(os.path.join(root, f))

./etl/build_tcga_pancan_expression_features.py
./data/processed/tcga_pancan_expression_summary_features.csv
./data/processed/.ipynb_checkpoints/tcga_pancan_expression_summary_features-checkpoint.csv

In [38]:
import os

keywords = ["tcga", "pancan", "xena", "gtex", "toil", "rsem", "fpkm", "tpm"]

for root, dirs, files in os.walk("."):
    for f in files:
        name = f.lower()
        if any(k in name for k in keywords):
            print(os.path.join(root, f))

./etl/build_tcga_pancan_expression_features.py
./etl/.ipynb_checkpoints/build_tcga_pancan_expression_features-checkpoint.py
./data/processed/tcga_pancan_expression_summary_features.csv
./data/processed/.ipynb_checkpoints/tcga_pancan_expression_summary_features-checkpoint.csv
./data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv

In [39]:
import pandas as pd

tcga_raw_path = "data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv"
tcga_raw = pd.read_csv(tcga_raw_path, sep="\t")

print("Raw TCGA shape:", tcga_raw.shape)
print("Columns (first 10):", tcga_raw.columns.tolist()[:10])
print(tcga_raw.head())

Raw TCGA shape: (20531, 11070)
Columns (first 10): ['gene_id', 'TCGA-OR-A5J1-01A-11R-A29S-07', 'TCGA-OR-A5J2-01A-11R-A29S-07', 'TCGA-OR-A5J3-01A-11R-A29S-07', 'TCGA-OR-A5J5-01A-11R-A29S-07', 'TCGA-OR-A5J6-01A-31R-A29S-07', 'TCGA-OR-A5J7-01A-11R-A29S-07', 'TCGA-OR-A5J8-01A-11R-A29S-07', 'TCGA-OR-A5J9-01A-11R-A29S-07', 'TCGA-OR-A5JA-01A-11R-A29S-07']
       gene_id  TCGA-OR-A5J1-01A-11R-A29S-07  TCGA-OR-A5J2-01A-11R-A29S-07  \
0  ?|100130426                        0.0000                        0.0000
1  ?|100133144                        3.2661                        2.6815
2  ?|100134869                        3.9385                        8.9948
3      ?|10357                      149.1350                       81.0777
4      ?|10431                     2034.1000                     1304.9300

   TCGA-OR-A5J3-01A-11R-A29S-07  TCGA-OR-A5J5-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        1.7301                        0.0000
2                        6.5650                        1.5492
3                       86.4879                       53.9117
4                     1054.6600                     2350.8900

   TCGA-OR-A5J6-01A-31R-A29S-07  TCGA-OR-A5J7-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        0.0000                        1.1673
2                        4.4709                        6.0529
3                       66.9063                      103.5060
4                     1257.9900                     1866.4300

   TCGA-OR-A5J8-01A-11R-A29S-07  TCGA-OR-A5J9-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        1.4422                        0.0000
2                        2.2876                        1.3599
3                       94.9316                       78.1955
4                      995.0270                     1762.1200

   TCGA-OR-A5JA-01A-11R-A29S-07  ...  TCGA-CG-4449-01A-01R-1157-13  \
0                        0.0000  ...                           NaN
1                        4.4556  ...                      4.358154
2                        5.0581  ...                      2.656360
3                       69.2389  ...                    633.299781
4                     1213.5300  ...                   1202.538277

   TCGA-CG-4462-01A-01R-1157-13  TCGA-CG-4465-01A-01R-1157-13  \
0                           NaN                           NaN
1                      5.676995                      5.219350
2                      3.342794                      2.423442
3                    294.018042                    686.569179
4                    644.002317                   1181.884532

   TCGA-CG-4466-01A-01R-1157-13  TCGA-CG-4469-01A-01R-1157-13  \
0                           NaN                           NaN
1                     14.846708                     20.115492
2                      5.055287                     11.626054
3                    563.573453                   1039.307597
4                    663.885074                    647.530395

   TCGA-CG-4472-01A-01R-1157-13  TCGA-CG-4474-01A-02R-1157-13  \
0                           NaN                           NaN
1                      6.997533                     18.311906
2                     13.654193                      7.417109
3                    639.238135                    742.479964
4                   1297.152549                   1152.909807

   TCGA-CG-4475-01A-01R-1157-13  TCGA-CG-4476-01A-01R-1157-13  \
0                           NaN                           NaN
1                     12.057112                     18.628740
2                     11.585177                     11.482418
3                    506.336449                    712.452165
4                   1375.495774                    971.893874

   TCGA-CG-4477-01A-01R-1157-13
0                           NaN
1                     17.874417
2                     14.919338
3                    703.713324
4                   1736.988111

[5 rows x 11070 columns]

In [40]:
import pandas as pd
import numpy as np

tcga_raw_path = "data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv"
tcga_raw = pd.read_csv(tcga_raw_path, sep="\t")

print("Raw TCGA shape:", tcga_raw.shape)

# 1) Split gene_id into symbol and entrez
gene_split = tcga_raw["gene_id"].astype(str).str.split("|", n=1, expand=True)
tcga_raw["gene_symbol"] = gene_split[0].str.strip()
tcga_raw["entrez_id"] = gene_split[1].str.strip()

# 2) Identify sample columns
sample_cols = [c for c in tcga_raw.columns if c not in ["gene_id", "gene_symbol", "entrez_id"]]
print("Number of sample columns:", len(sample_cols))

num = tcga_raw[sample_cols].apply(pd.to_numeric, errors="coerce")

# 3) Aggregate across samples
tcga_pancan_df = pd.DataFrame({
    "gene_symbol": tcga_raw["gene_symbol"],
    "expr_mean_tcga_pancan": num.mean(axis=1),
    "expr_median_tcga_pancan": num.median(axis=1),
    "expr_std_tcga_pancan": num.std(axis=1),
    "expr_min_tcga_pancan": num.min(axis=1),
    "expr_max_tcga_pancan": num.max(axis=1),
    "expr_q1_tcga_pancan": num.quantile(0.25, axis=1),
    "expr_q3_tcga_pancan": num.quantile(0.75, axis=1),
})

tcga_pancan_df["expr_iqr_tcga_pancan"] = (
    tcga_pancan_df["expr_q3_tcga_pancan"] - tcga_pancan_df["expr_q1_tcga_pancan"]
)
tcga_pancan_df["expr_prevalence_tcga_pancan"] = (num > 0).mean(axis=1)
tcga_pancan_df["in_tcga_pancan_expr"] = (tcga_pancan_df["expr_prevalence_tcga_pancan"] > 0).astype(int)

print("TCGA pancan summary shape:", tcga_pancan_df.shape)
print(tcga_pancan_df.head())

tcga_pancan_df.to_csv(
    "data/processed/tcga_pancan_expression_summary_features.csv",
    index=False
)

Raw TCGA shape: (20531, 11070)
Number of sample columns: 11069
TCGA pancan summary shape: (20531, 11)
  gene_symbol  expr_mean_tcga_pancan  expr_median_tcga_pancan  \
0           ?               0.028386                 0.000000
1           ?              11.251089                 7.809006
2           ?              11.670693                 8.640000
3           ?             160.950078               123.578000
4           ?             986.122273               905.364000

   expr_std_tcga_pancan  expr_min_tcga_pancan  expr_max_tcga_pancan  \
0              0.239364             -0.090423             17.995000
1             12.199371             -0.525753            187.474945
2             11.671968             -0.516280            402.218988
3            126.505719              0.000000           1995.021959
4            416.277222            232.315000           6818.118303

   expr_q1_tcga_pancan  expr_q3_tcga_pancan  expr_iqr_tcga_pancan  \
0               0.0000             0.000000              0.000000
1               3.4492            14.976397             11.527197
2               4.5975            14.987820             10.390320
3              85.2826           191.223000            105.940400
4             705.7730          1172.160000            466.387000

   expr_prevalence_tcga_pancan  in_tcga_pancan_expr
0                     0.041648                    1
1                     0.940284                    1
2                     0.976059                    1
3                     0.999819                    1
4                     1.000000                    1

In [41]:
import pandas as pd

# Load GEO-only summary and TCGA pancan summary
expr = pd.read_csv("data/processed/expression_summary_features.csv")
tcga = pd.read_csv("data/processed/tcga_pancan_expression_summary_features.csv")

print("expr shape:", expr.shape)
print("tcga shape:", tcga.shape)

# expr currently has no symbol; add it by merging with the existing annot file
annot_old = pd.read_csv("data/processed/expression_summary_features_annot.csv")

# annot_old has symbol but empty TCGA columns. We only need its symbol column.
annot_old = annot_old[["ensembl_id", "symbol"]].drop_duplicates()

# Normalize IDs
expr["ensembl_id"] = expr["ensembl_id"].astype(str).str.strip()
annot_old["ensembl_id"] = annot_old["ensembl_id"].astype(str).str.strip()

# Add symbol into expr
expr_with_symbol = expr.merge(annot_old, on="ensembl_id", how="left")

print("expr_with_symbol columns:", expr_with_symbol.columns.tolist()[:12])

# Normalize symbol in both tables
expr_with_symbol["symbol"] = expr_with_symbol["symbol"].astype(str).str.strip()
tcga["gene_symbol"] = tcga["gene_symbol"].astype(str).str.strip()

# Merge on symbol to bring in TCGA features
merged = expr_with_symbol.merge(
    tcga,
    left_on="symbol",
    right_on="gene_symbol",
    how="left",
    suffixes=("", "_tcga")
)

# Drop duplicate symbol column from tcga
if "gene_symbol" in merged.columns:
    merged = merged.drop(columns=["gene_symbol"])

print("Merged shape:", merged.shape)
print("Non-null TCGA counts:")
print(merged[[
    "expr_mean_tcga_pancan",
    "expr_prevalence_tcga_pancan",
    "in_tcga_pancan_expr"
]].notna().sum())

# Save new annot file
merged.to_csv("data/processed/expression_summary_features_annot.csv", index=False)

expr shape: (19786, 9)
tcga shape: (20531, 11)
expr_with_symbol columns: ['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max', 'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean', 'expr_log1p_max', 'symbol']
Merged shape: (19786, 20)
Non-null TCGA counts:
expr_mean_tcga_pancan          0
expr_prevalence_tcga_pancan    0
in_tcga_pancan_expr            0
dtype: int64

In [42]:
import pandas as pd

expr_annot = pd.read_csv("data/processed/expression_summary_features_annot.csv")
tcga = pd.read_csv("data/processed/tcga_pancan_expression_summary_features.csv")

expr_syms = set(expr_annot["symbol"].astype(str).str.strip())
tcga_syms = set(tcga["gene_symbol"].astype(str).str.strip())

print("Unique symbols in expr_annot:", len(expr_syms))
print("Unique symbols in tcga:", len(tcga_syms))
print("Overlap:", len(expr_syms & tcga_syms))

print("\nExample expr symbols (first 20):", sorted(list(expr_syms))[:20])
print("\nExample tcga symbols (first 20):", sorted(list(tcga_syms))[:20])

Unique symbols in expr_annot: 1
Unique symbols in tcga: 20502
Overlap: 0

Example expr symbols (first 20): ['nan']

Example tcga symbols (first 20): ['?', 'A1BG', 'A1CF', 'A2BP1', 'A2LD1', 'A2M', 'A2ML1', 'A4GALT', 'A4GNT', 'AAA1', 'AAAS', 'AACS', 'AACSL', 'AADAC', 'AADACL2', 'AADACL3', 'AADACL4', 'AADAT', 'AAGAB', 'AAK1']

In [1]:
import os
import sys

print("Current working directory:", os.getcwd())

project_root = "ncrna_platform"
print("Project exists:", os.path.isdir(project_root))

required = ["app", "configs", "data", "db", "etl", "models", "outputs", "scripts", "run_pipeline.py"]
for name in required:
    path = os.path.join(project_root, name)
    print(f"{name:15} ->", "OK" if (os.path.exists(path)) else "MISSING")

Current working directory: /Users/beshoyarmanios/ncrna_platform
Project exists: False
app             -> MISSING
configs         -> MISSING
data            -> MISSING
db              -> MISSING
etl             -> MISSING
models          -> MISSING
outputs         -> MISSING
scripts         -> MISSING
run_pipeline.py -> MISSING

In [2]:
import os
from pathlib import Path

cwd = Path(os.getcwd())
print("Current working directory:", cwd)

# If you're already in the project root, use '.'
project_root = cwd
print("Project root:", project_root)

required = ["app", "configs", "data", "db", "etl", "models", "outputs", "scripts", "run_pipeline.py"]
for name in required:
    path = project_root / name
    print(f"{name:15} ->", "OK" if path.exists() else "MISSING")

Current working directory: /Users/beshoyarmanios/ncrna_platform
Project root: /Users/beshoyarmanios/ncrna_platform
app             -> OK
configs         -> OK
data            -> OK
db              -> OK
etl             -> OK
models          -> OK
outputs         -> OK
scripts         -> OK
run_pipeline.py -> OK

In [3]:
import sys
from pathlib import Path

project_root = Path.cwd()
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from models.features import build_feature_matrix

df = build_feature_matrix()
print("Feature matrix shape:", df.shape)
print(df.filter(regex="expr_").head())

✅ Feature matrix: 12 ncRNAs × 53 features
Feature matrix shape: (12, 53)
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [4]:
print("Feature matrix shape:", df.shape)
print("First 10 columns:", list(df.columns[:10]))

# Look for anything containing 'expr' just to confirm
print("\nColumns containing 'expr':")
print([c for c in df.columns if "expr" in c.lower()])

# Show the first few rows of all features
df.head()

Feature matrix shape: (12, 53)
First 10 columns: ['ncrna_id', 'symbol', 'biotype', 'conservation_score', 'transcript_count', 'mean_abs_log2fc', 'mean_tau', 'n_sig_datasets', 'n_datasets', 'mean_tpm_disease']

Columns containing 'expr':
[]

,ncrna_id,symbol,biotype,conservation_score,transcript_count,mean_abs_log2fc,mean_tau,n_sig_datasets,n_datasets,mean_tpm_disease,...,curated_contradiction_flag,curated_hcc_flag,curated_masld_flag,curated_fibrosis_flag,curated_mash_flag,curated_record_count,curated_exists,risk_ubiquitous,risk_contradictory_lit,risk_high_isoforms
0,LNCRNA_001,HNF1A-AS1,lncRNA,0.82,3,2.1306,0.6444,1.0,5.0,86.890,...,0.0,0.0,1.0,0.0,0.0,1.0,1,0,0,0
1,LNCRNA_002,NEAT1,lncRNA,0.91,2,1.0496,0.5808,1.0,5.0,78.652,...,0.0,0.0,0.0,0.0,1.0,1.0,1,0,0,0
2,LNCRNA_003,MALAT1,lncRNA,0.95,1,0.6330,0.5312,1.0,5.0,107.064,...,0.0,1.0,0.0,0.0,0.0,1.0,1,0,0,0
3,LNCRNA_004,SNHG12,lncRNA,0.71,4,0.7088,0.6148,2.0,5.0,106.226,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
4,LNCRNA_005,HULC,lncRNA,0.55,2,2.2822,0.5282,0.0,5.0,80.708,...,0.0,1.0,0.0,0.0,0.0,1.0,1,0,0,0

In [5]:
numeric_cols = [
    "conservation_score",
    "transcript_count",
    "mean_abs_log2fc",
    "mean_tau",
    "n_sig_datasets",
    "n_datasets",
    "mean_tpm_disease",
]

print("Numeric feature summary:")
print(df[numeric_cols].describe())

Numeric feature summary:
       conservation_score  transcript_count  mean_abs_log2fc   mean_tau  \
count           12.000000         12.000000        12.000000  12.000000
mean             0.754167          3.166667         0.885783   0.510400
std              0.157333          2.208798         0.714830   0.252485
min              0.430000          1.000000         0.000000   0.000000
25%              0.695000          1.750000         0.583700   0.524550
50%              0.745000          2.500000         0.672500   0.569000
75%              0.887500          4.250000         1.105600   0.628200
max              0.950000          8.000000         2.282200   0.777400

       n_sig_datasets  n_datasets  mean_tpm_disease
count       12.000000   12.000000         12.000000
mean         0.750000    4.166667         79.211833
std          0.753778    1.946247         39.017056
min          0.000000    0.000000          0.000000
25%          0.000000    5.000000         80.032000
50%          1.000000    5.000000         91.370000
75%          1.000000    5.000000        100.095500
max          2.000000    5.000000        120.622000

In [6]:
for c in df.columns:
    print(c)

ncrna_id
symbol
biotype
conservation_score
transcript_count
mean_abs_log2fc
mean_tau
n_sig_datasets
n_datasets
mean_tpm_disease
n_up
n_down
de_consistency
log_tpm_disease
sig_rate
localization
isoform_count
gc_content
secondary_structure_score
aso_accessible
sirna_compatible
small_mol_bindable
crispr_feasible
best_modality
modality_breadth
nuclear_flag
isoform_complexity
n_perturbation_studies
mean_pert_effect
n_high_conf_perts
n_clinical_studies
mean_clinical_r
n_sig_clinical
n_prognostic
n_pathways
best_pathway_fdr
max_hub_correlation
n_lit_statements
mean_lit_confidence
n_contradictory
n_unique_papers
most_recent_year
curated_tier_score
curated_contradiction_flag
curated_hcc_flag
curated_masld_flag
curated_fibrosis_flag
curated_mash_flag
curated_record_count
curated_exists
risk_ubiquitous
risk_contradictory_lit
risk_high_isoforms

In [7]:
selected = ["mean_abs_log2fc", "mean_tpm_disease", "n_sig_datasets"]
df[selected].head()

   mean_abs_log2fc  mean_tpm_disease  n_sig_datasets
0           2.1306            86.890             1.0
1           1.0496            78.652             1.0
2           0.6330           107.064             1.0
3           0.7088           106.226             2.0
4           2.2822            80.708             0.0

In [8]:
from pathlib import Path

root = Path.cwd()
print("Working directory:", root)

required = [
    "app",
    "configs",
    "data",
    "db",
    "etl",
    "models",
    "outputs",
]

for x in required:
    p = root / x
    print(f"{x:10} ->", "OK" if p.exists() else "MISSING")

Working directory: /Users/beshoyarmanios/ncrna_platform
app        -> OK
configs    -> OK
data       -> OK
db         -> OK
etl        -> OK
models     -> OK
outputs    -> OK

In [9]:
import sys
from pathlib import Path

project_root = Path.cwd()
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from models.features import build_feature_matrix

df = build_feature_matrix()
print("Feature matrix shape:", df.shape)
print(df.head())

✅ Feature matrix: 12 ncRNAs × 53 features
Feature matrix shape: (12, 53)
     ncrna_id     symbol biotype  conservation_score  transcript_count  \
0  LNCRNA_001  HNF1A-AS1  lncRNA                0.82                 3
1  LNCRNA_002      NEAT1  lncRNA                0.91                 2
2  LNCRNA_003     MALAT1  lncRNA                0.95                 1
3  LNCRNA_004     SNHG12  lncRNA                0.71                 4
4  LNCRNA_005       HULC  lncRNA                0.55                 2

   mean_abs_log2fc  mean_tau  n_sig_datasets  n_datasets  mean_tpm_disease  \
0           2.1306    0.6444             1.0         5.0            86.890
1           1.0496    0.5808             1.0         5.0            78.652
2           0.6330    0.5312             1.0         5.0           107.064
3           0.7088    0.6148             2.0         5.0           106.226
4           2.2822    0.5282             0.0         5.0            80.708

   ...  curated_contradiction_flag  curated_hcc_flag  curated_masld_flag  \
0  ...                         0.0               0.0                 1.0
1  ...                         0.0               0.0                 0.0
2  ...                         0.0               1.0                 0.0
3  ...                         0.0               0.0                 0.0
4  ...                         0.0               1.0                 0.0

   curated_fibrosis_flag  curated_mash_flag curated_record_count  \
0                    0.0                0.0                  1.0
1                    0.0                1.0                  1.0
2                    0.0                0.0                  1.0
3                    0.0                0.0                  0.0
4                    0.0                0.0                  1.0

   curated_exists  risk_ubiquitous  risk_contradictory_lit  risk_high_isoforms
0               1                0                       0                   0
1               1                0                       0                   0
2               1                0                       0                   0
3               0                0                       0                   0
4               1                0                       0                   0

[5 rows x 53 columns]

In [10]:
print("Columns:")
for c in df.columns:
    print(c)

tcga_cols = [c for c in df.columns if "tcga" in c.lower()]
print("\nTCGA columns:", tcga_cols)

if tcga_cols:
    print("\nNon-null counts in TCGA columns:")
    print(df[tcga_cols].notna().sum())
else:
    print("\nNo TCGA columns found in feature matrix.")

Columns:
ncrna_id
symbol
biotype
conservation_score
transcript_count
mean_abs_log2fc
mean_tau
n_sig_datasets
n_datasets
mean_tpm_disease
n_up
n_down
de_consistency
log_tpm_disease
sig_rate
localization
isoform_count
gc_content
secondary_structure_score
aso_accessible
sirna_compatible
small_mol_bindable
crispr_feasible
best_modality
modality_breadth
nuclear_flag
isoform_complexity
n_perturbation_studies
mean_pert_effect
n_high_conf_perts
n_clinical_studies
mean_clinical_r
n_sig_clinical
n_prognostic
n_pathways
best_pathway_fdr
max_hub_correlation
n_lit_statements
mean_lit_confidence
n_contradictory
n_unique_papers
most_recent_year
curated_tier_score
curated_contradiction_flag
curated_hcc_flag
curated_masld_flag
curated_fibrosis_flag
curated_mash_flag
curated_record_count
curated_exists
risk_ubiquitous
risk_contradictory_lit
risk_high_isoforms

TCGA columns: []

No TCGA columns found in feature matrix.

In [11]:
from pathlib import Path
import pandas as pd

files_to_check = [
    "data/processed/expression_summary_features.csv",
    "data/processed/expression_summary_features_annot.csv",
    "data/processed/tcga_pancan_expression_summary_features.csv",
]

for f in files_to_check:
    p = Path(f)
    print(f"\nFILE: {f}")
    print("Exists:", p.exists())
    if p.exists():
        tmp = pd.read_csv(p)
        print("Shape:", tmp.shape)
        print("Columns:", list(tmp.columns[:20]))
        print("Has symbol:", "symbol" in tmp.columns)
        print("Has ensembl_id:", "ensembl_id" in tmp.columns)
        print("Has TCGA cols:", [c for c in tmp.columns if "tcga" in c.lower()][:10])

FILE: data/processed/expression_summary_features.csv
Exists: True
Shape: (19786, 9)
Columns: ['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max', 'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean', 'expr_log1p_max']
Has symbol: False
Has ensembl_id: True
Has TCGA cols: []

FILE: data/processed/expression_summary_features_annot.csv
Exists: True
Shape: (19786, 20)
Columns: ['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max', 'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean', 'expr_log1p_max', 'symbol', 'expr_mean_tcga_pancan', 'expr_median_tcga_pancan', 'expr_std_tcga_pancan', 'expr_min_tcga_pancan', 'expr_max_tcga_pancan', 'expr_q1_tcga_pancan', 'expr_q3_tcga_pancan', 'expr_iqr_tcga_pancan', 'expr_prevalence_tcga_pancan', 'in_tcga_pancan_expr']
Has symbol: True
Has ensembl_id: True
Has TCGA cols: ['expr_mean_tcga_pancan', 'expr_median_tcga_pancan', 'expr_std_tcga_pancan', 'expr_min_tcga_pancan', 'expr_max_tcga_pancan', 'expr_q1_tcga_pancan', 'expr_q3_tcga_pancan', 'expr_iqr_tcga_pancan', 'expr_prevalence_tcga_pancan', 'in_tcga_pancan_expr']

FILE: data/processed/tcga_pancan_expression_summary_features.csv
Exists: True
Shape: (20531, 11)
Columns: ['gene_symbol', 'expr_mean_tcga_pancan', 'expr_median_tcga_pancan', 'expr_std_tcga_pancan', 'expr_min_tcga_pancan', 'expr_max_tcga_pancan', 'expr_q1_tcga_pancan', 'expr_q3_tcga_pancan', 'expr_iqr_tcga_pancan', 'expr_prevalence_tcga_pancan', 'in_tcga_pancan_expr']
Has symbol: False
Has ensembl_id: False
Has TCGA cols: ['expr_mean_tcga_pancan', 'expr_median_tcga_pancan', 'expr_std_tcga_pancan', 'expr_min_tcga_pancan', 'expr_max_tcga_pancan', 'expr_q1_tcga_pancan', 'expr_q3_tcga_pancan', 'expr_iqr_tcga_pancan', 'expr_prevalence_tcga_pancan', 'in_tcga_pancan_expr']

In [12]:
import pandas as pd

expr_annot = pd.read_csv("data/processed/expression_summary_features_annot.csv")

print("Symbol null fraction:", expr_annot["symbol"].isna().mean())
print("TCGA mean non-null fraction:", expr_annot["expr_mean_tcga_pancan"].isna().mean())
print(expr_annot.head())

Symbol null fraction: 1.0
TCGA mean non-null fraction: 1.0
        ensembl_id    expr_mean     expr_std  expr_median  expr_max  \
0  ENSG00000000003  2535.210526  1043.461491       2422.0      5345
1  ENSG00000000005     3.456140     9.049606          0.0        58
2  ENSG00000000419   260.859649   102.360260        260.0       523
3  ENSG00000000457   203.245614    78.795685        205.0       454
4  ENSG00000000460    41.210526    20.740520         41.0        89

   expr_nonzero_fraction   expr_cv  expr_log1p_mean  expr_log1p_max  symbol  \
0               1.000000  0.411588         7.838426        8.584104     NaN
1               0.438596  2.618414         1.494283        4.077537     NaN
2               1.000000  0.392396         5.567809        6.261492     NaN
3               1.000000  0.387687         5.319323        6.120297     NaN
4               1.000000  0.503282         3.742670        4.499810     NaN

   expr_mean_tcga_pancan  expr_median_tcga_pancan  expr_std_tcga_pancan  \
0                    NaN                      NaN                   NaN
1                    NaN                      NaN                   NaN
2                    NaN                      NaN                   NaN
3                    NaN                      NaN                   NaN
4                    NaN                      NaN                   NaN

   expr_min_tcga_pancan  expr_max_tcga_pancan  expr_q1_tcga_pancan  \
0                   NaN                   NaN                  NaN
1                   NaN                   NaN                  NaN
2                   NaN                   NaN                  NaN
3                   NaN                   NaN                  NaN
4                   NaN                   NaN                  NaN

   expr_q3_tcga_pancan  expr_iqr_tcga_pancan  expr_prevalence_tcga_pancan  \
0                  NaN                   NaN                          NaN
1                  NaN                   NaN                          NaN
2                  NaN                   NaN                          NaN
3                  NaN                   NaN                          NaN
4                  NaN                   NaN                          NaN

   in_tcga_pancan_expr
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN

In [13]:
import pandas as pd
from pathlib import Path

expr_path = Path("data/processed/expression_summary_features.csv")
map_path = Path("data/raw/ensembl_to_symbol.csv")

expr = pd.read_csv(expr_path)
mapping = pd.read_csv(map_path)

print("expr shape:", expr.shape)
print("mapping shape:", mapping.shape)

print("\nexpr columns:")
print(expr.columns.tolist())

print("\nmapping columns:")
print(mapping.columns.tolist())

print("\nexpr head:")
print(expr.head(3))

print("\nmapping head:")
print(mapping.head(3))

expr shape: (19786, 9)
mapping shape: (12, 2)

expr columns:
['ensembl_id', 'expr_mean', 'expr_std', 'expr_median', 'expr_max', 'expr_nonzero_fraction', 'expr_cv', 'expr_log1p_mean', 'expr_log1p_max']

mapping columns:
['symbol', 'ensembl_id']

expr head:
        ensembl_id    expr_mean     expr_std  expr_median  expr_max  \
0  ENSG00000000003  2535.210526  1043.461491       2422.0      5345
1  ENSG00000000005     3.456140     9.049606          0.0        58
2  ENSG00000000419   260.859649   102.360260        260.0       523

   expr_nonzero_fraction   expr_cv  expr_log1p_mean  expr_log1p_max
0               1.000000  0.411588         7.838426        8.584104
1               0.438596  2.618414         1.494283        4.077537
2               1.000000  0.392396         5.567809        6.261492

mapping head:
      symbol       ensembl_id
0  HNF1A-AS1  ENSG00000241388
1      NEAT1  ENSG00000245532
2     MALAT1  ENSG00000251562

In [15]:
import pandas as pd
from pathlib import Path

expr_path = Path("data/processed/expression_summary_features.csv")
map_path = Path("data/raw/ensembl_to_symbol.csv")

expr = pd.read_csv(expr_path)
mapping = pd.read_csv(map_path)

def strip_version(s: pd.Series) -> pd.Series:
    return s.astype(str).str.split(".").str[0]

expr["ensembl_id_norm"] = strip_version(expr["ensembl_id"])
mapping["ensembl_id_norm"] = strip_version(mapping["ensembl_id"])

# Merge to add symbol
expr_annot_new = expr.merge(
    mapping[["ensembl_id_norm", "symbol"]],
    on="ensembl_id_norm",
    how="left",
)

# Drop the helper column and just keep symbol where available
expr_annot_new = expr_annot_new.drop(columns=["ensembl_id_norm"])

# Put symbol right after ensembl_id for readability
cols = expr_annot_new.columns.tolist()
cols.remove("symbol")
cols.insert(1, "symbol")
expr_annot_new = expr_annot_new[cols]

print("New annotated shape:", expr_annot_new.shape)
print("Symbol null fraction:", expr_annot_new["symbol"].isna().mean())
print(expr_annot_new.head(15))

New annotated shape: (19786, 10)
Symbol null fraction: 1.0
         ensembl_id symbol     expr_mean      expr_std  expr_median  expr_max  \
0   ENSG00000000003    NaN   2535.210526   1043.461491       2422.0      5345
1   ENSG00000000005    NaN      3.456140      9.049606          0.0        58
2   ENSG00000000419    NaN    260.859649    102.360260        260.0       523
3   ENSG00000000457    NaN    203.245614     78.795685        205.0       454
4   ENSG00000000460    NaN     41.210526     20.740520         41.0        89
5   ENSG00000000938    NaN     56.684211     31.854669         49.0       171
6   ENSG00000000971    NaN  32927.701754  20112.100865      30897.0     92811
7   ENSG00000001036    NaN    903.614035    424.388036        778.0      1902
8   ENSG00000001084    NaN   1722.771930    793.012813       1707.0      3515
9   ENSG00000001167    NaN    138.543860     76.939928        137.0       326
10  ENSG00000001460    NaN     23.543860     10.199913         22.0        50
11  ENSG00000001461    NaN    144.421053     72.297240        140.0       365
12  ENSG00000001497    NaN    387.210526    206.895310        338.0       882
13  ENSG00000001561    NaN    124.491228     69.016593        115.0       331
14  ENSG00000001617    NaN    103.298246     56.690250         93.0       229

    expr_nonzero_fraction   expr_cv  expr_log1p_mean  expr_log1p_max
0                1.000000  0.411588         7.838426        8.584104
1                0.438596  2.618414         1.494283        4.077537
2                1.000000  0.392396         5.567809        6.261492
3                1.000000  0.387687         5.319323        6.120297
4                1.000000  0.503282         3.742670        4.499810
5                1.000000  0.561967         4.054983        5.147494
6                1.000000  0.610796        10.402100       11.438331
7                1.000000  0.469656         6.807508        7.551187
8                1.000000  0.460312         7.452270        8.165079
9                1.000000  0.555347         4.938379        5.789960
10               1.000000  0.433230         3.200462        3.931826
11               1.000000  0.500600         4.979633        5.902633
12               1.000000  0.534323         5.961548        6.783325
13               1.000000  0.554389         4.832236        5.805135
14               1.000000  0.548802         4.647255        5.438079

In [16]:
panel = [
    "HNF1A-AS1",
    "NEAT1",
    "MALAT1",
    "SNHG12",
    "HULC",
    "HOTAIR",
    "GAS5",
    "LINC01116",
    "MIAT",
    "XIST",
    "H19",
    "MEG3",
]

print("Mapping table rows:")
print(mapping)

# Check how many of these symbols have a mapping
mapped_symbols = set(mapping["symbol"])
print("\nSymbols in panel that have mappings:")
print([s for s in panel if s in mapped_symbols])

# Now, for the mapped ones, show expr_annot_new rows
expr_panel = expr_annot_new[expr_annot_new["symbol"].isin(mapped_symbols)]
print("\nexpr_annot_new rows with non-null symbol:")
print(expr_panel.head(20))
print("\nCount with non-null symbol:", expr_panel.shape[0])

Mapping table rows:
       symbol       ensembl_id  ensembl_id_norm
0   HNF1A-AS1  ENSG00000241388  ENSG00000241388
1       NEAT1  ENSG00000245532  ENSG00000245532
2      MALAT1  ENSG00000251562  ENSG00000251562
3      SNHG12  ENSG00000245910  ENSG00000245910
4        HULC  ENSG00000251164  ENSG00000251164
5      HOTAIR  ENSG00000228630  ENSG00000228630
6        GAS5  ENSG00000234741  ENSG00000234741
7   LINC01116  ENSG00000226549  ENSG00000226549
8        MIAT  ENSG00000225783  ENSG00000225783
9        XIST  ENSG00000229807  ENSG00000229807
10        H19  ENSG00000130600  ENSG00000130600
11       MEG3  ENSG00000214548  ENSG00000214548

Symbols in panel that have mappings:
['HNF1A-AS1', 'NEAT1', 'MALAT1', 'SNHG12', 'HULC', 'HOTAIR', 'GAS5', 'LINC01116', 'MIAT', 'XIST', 'H19', 'MEG3']

expr_annot_new rows with non-null symbol:
Empty DataFrame
Columns: [ensembl_id, symbol, expr_mean, expr_std, expr_median, expr_max, expr_nonzero_fraction, expr_cv, expr_log1p_mean, expr_log1p_max]
Index: []

Count with non-null symbol: 0

In [17]:
import pandas as pd
from pathlib import Path

tcga_raw_path = Path("data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv")

tcga_raw = pd.read_csv(tcga_raw_path, sep="\t")

print("Raw TCGA shape:", tcga_raw.shape)
print("TCGA columns (first 10):")
print(tcga_raw.columns[:10].tolist())

print("\nHead:")
print(tcga_raw.head(5))

Raw TCGA shape: (20531, 11070)
TCGA columns (first 10):
['gene_id', 'TCGA-OR-A5J1-01A-11R-A29S-07', 'TCGA-OR-A5J2-01A-11R-A29S-07', 'TCGA-OR-A5J3-01A-11R-A29S-07', 'TCGA-OR-A5J5-01A-11R-A29S-07', 'TCGA-OR-A5J6-01A-31R-A29S-07', 'TCGA-OR-A5J7-01A-11R-A29S-07', 'TCGA-OR-A5J8-01A-11R-A29S-07', 'TCGA-OR-A5J9-01A-11R-A29S-07', 'TCGA-OR-A5JA-01A-11R-A29S-07']

Head:
       gene_id  TCGA-OR-A5J1-01A-11R-A29S-07  TCGA-OR-A5J2-01A-11R-A29S-07  \
0  ?|100130426                        0.0000                        0.0000
1  ?|100133144                        3.2661                        2.6815
2  ?|100134869                        3.9385                        8.9948
3      ?|10357                      149.1350                       81.0777
4      ?|10431                     2034.1000                     1304.9300

   TCGA-OR-A5J3-01A-11R-A29S-07  TCGA-OR-A5J5-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        1.7301                        0.0000
2                        6.5650                        1.5492
3                       86.4879                       53.9117
4                     1054.6600                     2350.8900

   TCGA-OR-A5J6-01A-31R-A29S-07  TCGA-OR-A5J7-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        0.0000                        1.1673
2                        4.4709                        6.0529
3                       66.9063                      103.5060
4                     1257.9900                     1866.4300

   TCGA-OR-A5J8-01A-11R-A29S-07  TCGA-OR-A5J9-01A-11R-A29S-07  \
0                        0.0000                        0.0000
1                        1.4422                        0.0000
2                        2.2876                        1.3599
3                       94.9316                       78.1955
4                      995.0270                     1762.1200

   TCGA-OR-A5JA-01A-11R-A29S-07  ...  TCGA-CG-4449-01A-01R-1157-13  \
0                        0.0000  ...                           NaN
1                        4.4556  ...                      4.358154
2                        5.0581  ...                      2.656360
3                       69.2389  ...                    633.299781
4                     1213.5300  ...                   1202.538277

   TCGA-CG-4462-01A-01R-1157-13  TCGA-CG-4465-01A-01R-1157-13  \
0                           NaN                           NaN
1                      5.676995                      5.219350
2                      3.342794                      2.423442
3                    294.018042                    686.569179
4                    644.002317                   1181.884532

   TCGA-CG-4466-01A-01R-1157-13  TCGA-CG-4469-01A-01R-1157-13  \
0                           NaN                           NaN
1                     14.846708                     20.115492
2                      5.055287                     11.626054
3                    563.573453                   1039.307597
4                    663.885074                    647.530395

   TCGA-CG-4472-01A-01R-1157-13  TCGA-CG-4474-01A-02R-1157-13  \
0                           NaN                           NaN
1                      6.997533                     18.311906
2                     13.654193                      7.417109
3                    639.238135                    742.479964
4                   1297.152549                   1152.909807

   TCGA-CG-4475-01A-01R-1157-13  TCGA-CG-4476-01A-01R-1157-13  \
0                           NaN                           NaN
1                     12.057112                     18.628740
2                     11.585177                     11.482418
3                    506.336449                    712.452165
4                   1375.495774                    971.893874

   TCGA-CG-4477-01A-01R-1157-13
0                           NaN
1                     17.874417
2                     14.919338
3                    703.713324
4                   1736.988111

[5 rows x 11070 columns]

In [19]:
from pathlib import Path

raw_dir = Path("data/raw")
print("Contents of data/raw:")
for p in raw_dir.iterdir():
    print("-", p.name)

Contents of data/raw:
- GSE126848_Gene_counts_raw.txt.gz
- EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv
- ensembl_to_symbol.csv
- GSE126848_series_matrix.txt.gz
- .ipynb_checkpoints

In [20]:
import pandas as pd
from pathlib import Path

tcga_path = Path("data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv")

# Load only the gene_id column first to keep memory low
gene_ids = pd.read_csv(tcga_path, sep="\t", usecols=["gene_id"])

print("Total rows:", len(gene_ids))
print("\nFirst 20 gene_id values:")
print(gene_ids["gene_id"].head(20).tolist())

print("\nSample of unique gene_id patterns:")
print(gene_ids["gene_id"].sample(20, random_state=42).tolist())

# Check if any look like Ensembl IDs (start with ENSG)
ensg_mask = gene_ids["gene_id"].astype(str).str.contains("ENSG", na=False)
print("\nRows with ENSG identifiers:", ensg_mask.sum())

# Check format: most are symbol|entrez like BRCA1|672
pipe_mask = gene_ids["gene_id"].astype(str).str.contains("|", regex=False, na=False)
print("Rows with pipe '|' format:", pipe_mask.sum())

# Show examples of non-'?' entries
real_ids = gene_ids[~gene_ids["gene_id"].astype(str).str.startswith("?")]
print("\nNon-'?' gene_id examples (first 20):")
print(real_ids.head(20).tolist())

Total rows: 20531

First 20 gene_id values:
['?|100130426', '?|100133144', '?|100134869', '?|10357', '?|10431', '?|136542', '?|155060', '?|26823', '?|280660', '?|317712', '?|340602', '?|388795', '?|390284', '?|391343', '?|391714', '?|404770', '?|441362', '?|442388', '?|553137', '?|57714']

Sample of unique gene_id patterns:
['ATP9A|10079', 'CCL17|6361', 'FHOD3|80206', 'SNORD115-22|100033799', 'OR2B3|442184', 'GEFT|115557', 'FAM133B|257415', 'TCEAL1|9338', 'MORN5|254956', 'PTPLB|201562', 'CCL25|6370', 'KIAA0895L|653319', 'CHRM4|1132', 'OR8K5|219453', 'LOC643719|643719', 'SCGB1A1|7356', 'SLC47A2|146802', 'SNAR-G2|100170228', 'CCDC150|284992', 'MORF4L2|9643']

Rows with ENSG identifiers: 0
Rows with pipe '|' format: 20531

Non-'?' gene_id examples (first 20):

AttributeError: 'DataFrame' object has no attribute 'tolist'

In [21]:
import pandas as pd
from pathlib import Path

tcga_path = Path("data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv")

# Load only gene_id column to inspect
gene_ids = pd.read_csv(tcga_path, sep="\t", usecols=["gene_id"])

# Split symbol|entrez into two columns
gene_ids[["gene_symbol", "entrez_id"]] = gene_ids["gene_id"].str.split("|", expand=True)

# Check your 12 ncRNA panel specifically
panel = ["HNF1A-AS1", "NEAT1", "MALAT1", "SNHG12", "HULC",
         "HOTAIR", "GAS5", "LINC01116", "MIAT", "XIST", "H19", "MEG3"]

found = gene_ids[gene_ids["gene_symbol"].isin(panel)]
print("Panel ncRNAs found in TCGA file:")
print(found[["gene_id", "gene_symbol", "entrez_id"]].to_string())
print(f"\n{len(found)} of {len(panel)} panel ncRNAs found")

Panel ncRNAs found in TCGA file:
                gene_id gene_symbol  entrez_id
6869         GAS5|60674        GAS5      60674
7591         H19|283120         H19     283120
8001   HOTAIR|100124700      HOTAIR  100124700
8193        HULC|728655        HULC     728655
10523     MALAT1|378938      MALAT1     378938
10791        MEG3|55384        MEG3      55384
10924       MIAT|440823        MIAT     440823
11749      NEAT1|283131       NEAT1     283131
16592      SNHG12|85028      SNHG12      85028
19663         XIST|7503        XIST       7503

10 of 12 panel ncRNAs found

In [22]:
import pandas as pd
import numpy as np
from pathlib import Path

tcga_path = Path("data/raw/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv")

# Load full matrix (this will take 30-60 seconds given file size)
print("Loading TCGA matrix...")
tcga_full = pd.read_csv(tcga_path, sep="\t", index_col=0, low_memory=False)
print("Loaded. Shape:", tcga_full.shape)

# Split gene_id index into symbol and entrez
tcga_full["gene_symbol"] = tcga_full.index.astype(str).str.split("|").str[0]

# Filter to your panel
panel = ["GAS5", "H19", "HOTAIR", "HULC", "MALAT1",
         "MEG3", "MIAT", "NEAT1", "SNHG12", "XIST"]

tcga_panel = tcga_full[tcga_full["gene_symbol"].isin(panel)].copy()
print("\nPanel rows extracted:", tcga_panel.shape)

# Drop the gene_symbol column before computing stats
sample_cols = [c for c in tcga_panel.columns if c != "gene_symbol"]
expr_vals = tcga_panel[sample_cols].astype(float)

# Compute pancan summary stats per ncRNA
stats = pd.DataFrame({
    "gene_symbol":            tcga_panel["gene_symbol"].values,
    "expr_mean_tcga_pancan":  expr_vals.mean(axis=1).values,
    "expr_median_tcga_pancan":expr_vals.median(axis=1).values,
    "expr_std_tcga_pancan":   expr_vals.std(axis=1).values,
    "expr_min_tcga_pancan":   expr_vals.min(axis=1).values,
    "expr_max_tcga_pancan":   expr_vals.max(axis=1).values,
    "expr_q1_tcga_pancan":    expr_vals.quantile(0.25, axis=1).values,
    "expr_q3_tcga_pancan":    expr_vals.quantile(0.75, axis=1).values,
    "expr_iqr_tcga_pancan":   (expr_vals.quantile(0.75, axis=1) - expr_vals.quantile(0.25, axis=1)).values,
    "expr_prevalence_tcga_pancan": (expr_vals > 0).mean(axis=1).values,
    "in_tcga_pancan_expr":    1,
})

print("\nTCGA pancan stats for panel ncRNAs:")
print(stats.to_string(index=False))

Loading TCGA matrix...
Loaded. Shape: (20531, 11069)

Panel rows extracted: (10, 11070)

TCGA pancan stats for panel ncRNAs:
gene_symbol  expr_mean_tcga_pancan  expr_median_tcga_pancan  expr_std_tcga_pancan  expr_min_tcga_pancan  expr_max_tcga_pancan  expr_q1_tcga_pancan  expr_q3_tcga_pancan  expr_iqr_tcga_pancan  expr_prevalence_tcga_pancan  in_tcga_pancan_expr
       GAS5            2396.315699              1732.370000           2418.685196            148.294000          5.048450e+04            1069.6100          2841.630000           1772.020000                     1.000000                    1
        H19           16457.563256              1279.110000          88043.125977              0.000000          4.682120e+06             347.3440          4516.680000           4169.336000                     0.999910                    1
     HOTAIR              32.148565                 3.047550            121.751617             -0.275567          7.937710e+03               0.0000            17.716725             17.716725                     0.716235                    1
       HULC             244.536891                 0.000000           1774.257500             -0.072964          5.305650e+04               0.0000             0.583175              0.583175                     0.400217                    1
     MALAT1            4113.415008              2456.990000           5765.734516             41.124700          1.090134e+05            1367.5300          4588.410000           3220.880000                     1.000000                    1
       MEG3             628.060871                43.867100           2914.970182              0.000000          6.568050e+04              14.0311           141.191000            127.159900                     0.988798                    1
       MIAT             468.775911               119.190000           1469.307265             -0.007404          4.565550e+04              49.4279           328.938000            279.510100                     0.999819                    1
      NEAT1           12035.397508              7605.220000          13908.525749             80.033100          3.269250e+05            3719.1700         15268.700000          11549.530000                     1.000000                    1
     SNHG12             309.776139               246.273000            248.383756              4.250800          3.570240e+03             139.6750           408.543000            268.868000                     1.000000                    1
       XIST            4477.996169               369.085378           8418.592223             -0.243921          3.619420e+05               2.3199          6512.070000           6509.750100                     0.896377                    1

In [23]:
import pandas as pd
import numpy as np
from pathlib import Path

# --- HNF1A-AS1: search by alternative names in TCGA ---
print("Searching for HNF1A-AS1 and LINC01116 alternatives...")
tcga_full_sym = tcga_full.copy()
tcga_full_sym["gene_symbol"] = tcga_full_sym.index.astype(str).str.split("|").str[0]

# Search for partial matches
for query in ["HNF1A", "LINC01116", "LINC1116"]:
    matches = tcga_full_sym[tcga_full_sym["gene_symbol"].str.contains(query, case=False, na=False)]
    print(f"\nMatches for '{query}':")
    print(matches["gene_symbol"].tolist())

# --- Add placeholder rows for missing ncRNAs with NaN TCGA values ---
missing_ncRNAs = ["HNF1A-AS1", "LINC01116"]

missing_rows = pd.DataFrame({
    "gene_symbol":                missing_ncRNAs,
    "expr_mean_tcga_pancan":      np.nan,
    "expr_median_tcga_pancan":    np.nan,
    "expr_std_tcga_pancan":       np.nan,
    "expr_min_tcga_pancan":       np.nan,
    "expr_max_tcga_pancan":       np.nan,
    "expr_q1_tcga_pancan":        np.nan,
    "expr_q3_tcga_pancan":        np.nan,
    "expr_iqr_tcga_pancan":       np.nan,
    "expr_prevalence_tcga_pancan":np.nan,
    "in_tcga_pancan_expr":        0,
})

# --- Combine 10 found + 2 missing ---
tcga_panel_full = pd.concat([stats, missing_rows], ignore_index=True)

print("\nFinal panel TCGA summary (12 ncRNAs):")
print(tcga_panel_full[["gene_symbol", "expr_mean_tcga_pancan", "in_tcga_pancan_expr"]].to_string(index=False))

# --- Save to processed folder ---
out_path = Path("data/processed/tcga_pancan_expression_summary_features.csv")
tcga_panel_full.to_csv(out_path, index=False)
print(f"\nSaved to {out_path}")
print("Shape:", tcga_panel_full.shape)

Searching for HNF1A-AS1 and LINC01116 alternatives...

Matches for 'HNF1A':
['HNF1A']

Matches for 'LINC01116':
[]

Matches for 'LINC1116':
[]

Final panel TCGA summary (12 ncRNAs):
gene_symbol  expr_mean_tcga_pancan  in_tcga_pancan_expr
       GAS5            2396.315699                    1
        H19           16457.563256                    1
     HOTAIR              32.148565                    1
       HULC             244.536891                    1
     MALAT1            4113.415008                    1
       MEG3             628.060871                    1
       MIAT             468.775911                    1
      NEAT1           12035.397508                    1
     SNHG12             309.776139                    1
       XIST            4477.996169                    1
  HNF1A-AS1                    NaN                    0
  LINC01116                    NaN                    0

Saved to data/processed/tcga_pancan_expression_summary_features.csv
Shape: (12, 11)

In [24]:
import pandas as pd
import numpy as np
from pathlib import Path
import os

# Make sure we're working from the project root
os.chdir('/Users/beshoyarmanios/ncrna_platform')
print('Working dir:', os.getcwd())

# Load all three sources
expr = pd.read_csv('data/processed/expression_summary_features.csv')
mapping = pd.read_csv('data/raw/ensembl_to_symbol.csv')
tcga_summary = pd.read_csv('data/processed/tcga_pancan_expression_summary_features.csv')

# Step 1: Add symbol to GEO summary via ensembl_id
expr_annot = expr.merge(mapping[['ensembl_id', 'symbol']], on='ensembl_id', how='left')

# Step 2: Reorder so symbol is right after ensembl_id
cols = expr_annot.columns.tolist()
cols.remove('symbol')
cols.insert(1, 'symbol')
expr_annot = expr_annot[cols]

# Step 3: Merge TCGA summary by symbol
expr_annot = expr_annot.merge(tcga_summary, left_on='symbol', right_on='gene_symbol', how='left')

# Drop redundant gene_symbol column
if 'gene_symbol' in expr_annot.columns:
    expr_annot = expr_annot.drop(columns=['gene_symbol'])

# Step 4: Save
out_path = Path('data/processed/expression_summary_features_annot.csv')
expr_annot.to_csv(out_path, index=False)
print('Saved:', out_path)
print('Shape:', expr_annot.shape)

# Step 5: Validate the 12 ncRNAs
panel_rows = expr_annot[expr_annot['symbol'].notna()]
print(f'\nRows with non-null symbol: {len(panel_rows)}')
print('\nPanel ncRNA rows:')
print(panel_rows[['ensembl_id', 'symbol', 'expr_mean', 'expr_mean_tcga_pancan', 'in_tcga_pancan_expr']].to_string(index=False))

FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/expression_summary_features.csv'

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

# Load all three sources
expr = pd.read_csv("data/processed/expression_summary_features.csv")
mapping = pd.read_csv("data/raw/ensembl_to_symbol.csv")
tcga_summary = pd.read_csv("data/processed/tcga_pancan_expression_summary_features.csv")

# Step 1: Add symbol to GEO summary via ensembl_id
expr_annot = expr.merge(mapping[["ensembl_id", "symbol"]], on="ensembl_id", how="left")

# Step 2: Reorder so symbol is right after ensembl_id
cols = expr_annot.columns.tolist()
cols.remove("symbol")
cols.insert(1, "symbol")
expr_annot = expr_annot[cols]

# Step 3: Merge TCGA summary by symbol
expr_annot = expr_annot.merge(tcga_summary, left_on="symbol", right_on="gene_symbol", how="left")

# Drop redundant gene_symbol column from TCGA
if "gene_symbol" in expr_annot.columns:
    expr_annot = expr_annot.drop(columns=["gene_symbol"])

# Step 4: Save
out_path = Path("data/processed/expression_summary_features_annot.csv")
expr_annot.to_csv(out_path, index=False)
print("Saved:", out_path)
print("Shape:", expr_annot.shape)

# Step 5: Validate the 12 ncRNAs specifically
panel_rows = expr_annot[expr_annot["symbol"].notna()]
print(f"\nRows with non-null symbol: {len(panel_rows)}")
print("\nPanel ncRNA rows:")
print(panel_rows[["ensembl_id", "symbol", "expr_mean", "expr_mean_tcga_pancan", "in_tcga_pancan_expr"]].to_string(index=False))

In [25]:
import pandas as pd
import numpy as np
from pathlib import Path

# Load all three sources
expr = pd.read_csv("data/processed/expression_summary_features.csv")
mapping = pd.read_csv("data/raw/ensembl_to_symbol.csv")
tcga_summary = pd.read_csv("data/processed/tcga_pancan_expression_summary_features.csv")

# Step 1: Add symbol to GEO summary via ensembl_id
expr_annot = expr.merge(mapping[["ensembl_id", "symbol"]], on="ensembl_id", how="left")

# Step 2: Reorder so symbol is right after ensembl_id
cols = expr_annot.columns.tolist()
cols.remove("symbol")
cols.insert(1, "symbol")
expr_annot = expr_annot[cols]

# Step 3: Merge TCGA summary by symbol
expr_annot = expr_annot.merge(tcga_summary, left_on="symbol", right_on="gene_symbol", how="left")

# Drop redundant gene_symbol column from TCGA
if "gene_symbol" in expr_annot.columns:
    expr_annot = expr_annot.drop(columns=["gene_symbol"])

# Step 4: Save
out_path = Path("data/processed/expression_summary_features_annot.csv")
expr_annot.to_csv(out_path, index=False)
print("Saved:", out_path)
print("Shape:", expr_annot.shape)

# Step 5: Validate the 12 ncRNAs specifically
panel_rows = expr_annot[expr_annot["symbol"].notna()]
print(f"\nRows with non-null symbol: {len(panel_rows)}")
print("\nPanel ncRNA rows:")
print(panel_rows[["ensembl_id", "symbol", "expr_mean", "expr_mean_tcga_pancan", "in_tcga_pancan_expr"]].to_string(index=False))

FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/expression_summary_features.csv'

In [26]:
import importlib
import sys
from pathlib import Path
import os

os.chdir('/Users/beshoyarmanios/ncrna_platform')

# Force reload of the features module to pick up new data
if 'models.features' in sys.modules:
    del sys.modules['models.features']

from models.features import build_feature_matrix

df = build_feature_matrix()
print('Feature matrix shape:', df.shape)

tcga_cols = [c for c in df.columns if 'tcga' in c.lower()]
print('TCGA columns:', tcga_cols)

if tcga_cols:
    print('\nTCGA values for panel:')
    print(df[['symbol'] + tcga_cols].to_string(index=False))

✅ Feature matrix: 12 ncRNAs × 53 features
Feature matrix shape: (12, 53)
TCGA columns: []

In [27]:
import importlib
import sys
import os

os.chdir('/Users/beshoyarmanios/ncrna_platform')

# Force full reload
for mod in list(sys.modules.keys()):
    if 'models' in mod or 'features' in mod:
        del sys.modules[mod]

from models.features import build_feature_matrix

df = build_feature_matrix()
print('Feature matrix shape:', df.shape)

tcga_cols = [c for c in df.columns if 'tcga' in c.lower()]
print('TCGA columns found:', len(tcga_cols))
print(tcga_cols)

if tcga_cols:
    print('\nTCGA values:')
    print(df[['symbol'] + tcga_cols].to_string(index=False))

✅ Feature matrix: 12 ncRNAs × 72 features
Feature matrix shape: (12, 72)
TCGA columns found: 10
['expr_mean_tcga_pancan', 'expr_median_tcga_pancan', 'expr_std_tcga_pancan', 'expr_min_tcga_pancan', 'expr_max_tcga_pancan', 'expr_q1_tcga_pancan', 'expr_q3_tcga_pancan', 'expr_iqr_tcga_pancan', 'expr_prevalence_tcga_pancan', 'in_tcga_pancan_expr']

TCGA values:
   symbol  expr_mean_tcga_pancan  expr_median_tcga_pancan  expr_std_tcga_pancan  expr_min_tcga_pancan  expr_max_tcga_pancan  expr_q1_tcga_pancan  expr_q3_tcga_pancan  expr_iqr_tcga_pancan  expr_prevalence_tcga_pancan  in_tcga_pancan_expr
HNF1A-AS1               0.000000                 0.000000              0.000000              0.000000          0.000000e+00               0.0000             0.000000              0.000000                     0.000000                    0
    NEAT1           12035.397508              7605.220000          13908.525749             80.033100          3.269250e+05            3719.1700         15268.700000          11549.530000                     1.000000                    1
   MALAT1            4113.415008              2456.990000           5765.734516             41.124700          1.090134e+05            1367.5300          4588.410000           3220.880000                     1.000000                    1
   SNHG12             309.776139               246.273000            248.383756              4.250800          3.570240e+03             139.6750           408.543000            268.868000                     1.000000                    1
     HULC             244.536891                 0.000000           1774.257500             -0.072964          5.305650e+04               0.0000             0.583175              0.583175                     0.400217                    1
   HOTAIR              32.148565                 3.047550            121.751617             -0.275567          7.937710e+03               0.0000            17.716725             17.716725                     0.716235                    1
     GAS5            2396.315699              1732.370000           2418.685196            148.294000          5.048450e+04            1069.6100          2841.630000           1772.020000                     1.000000                    1
LINC01116               0.000000                 0.000000              0.000000              0.000000          0.000000e+00               0.0000             0.000000              0.000000                     0.000000                    0
     MIAT             468.775911               119.190000           1469.307265             -0.007404          4.565550e+04              49.4279           328.938000            279.510100                     0.999819                    1
     XIST            4477.996169               369.085378           8418.592223             -0.243921          3.619420e+05               2.3199          6512.070000           6509.750100                     0.896377                    1
      H19           16457.563256              1279.110000          88043.125977              0.000000          4.682120e+06             347.3440          4516.680000           4169.336000                     0.999910                    1
     MEG3             628.060871                43.867100           2914.970182              0.000000          6.568050e+04              14.0311           141.191000            127.159900                     0.988798                    1

In [28]:
import sys, os
os.chdir('/Users/beshoyarmanios/ncrna_platform')
if str(os.getcwd()) not in sys.path:
    sys.path.insert(0, os.getcwd())

# Force fresh reload
for mod in list(sys.modules.keys()):
    if 'models' in mod:
        del sys.modules[mod]

from models.features import build_feature_matrix

df = build_feature_matrix()

print("=" * 50)
print("ncRNA PLATFORM — DEMO READY CHECK")
print("=" * 50)
print(f"Feature matrix: {df.shape[0]} ncRNAs × {df.shape[1]} features")
print(f"TCGA columns:   {len([c for c in df.columns if 'tcga' in c.lower()])}")
print(f"Curated flags:  {len([c for c in df.columns if 'curated' in c.lower()])}")
print(f"Risk scores:    {len([c for c in df.columns if 'risk' in c.lower()])}")
print()
print("Top ncRNAs by TCGA pan-cancer mean expression:")
print(df[['symbol','expr_mean_tcga_pancan','mean_abs_log2fc','curated_exists']]\
      .sort_values('expr_mean_tcga_pancan', ascending=False)\
      .to_string(index=False))

✅ Feature matrix: 12 ncRNAs × 72 features
==================================================
ncRNA PLATFORM — DEMO READY CHECK
==================================================
Feature matrix: 12 ncRNAs × 72 features
TCGA columns:   10
Curated flags:  8
Risk scores:    3

Top ncRNAs by TCGA pan-cancer mean expression:
   symbol  expr_mean_tcga_pancan  mean_abs_log2fc  curated_exists
      H19           16457.563256           0.0000               1
    NEAT1           12035.397508           1.0496               1
     XIST            4477.996169           0.6362               0
   MALAT1            4113.415008           0.6330               1
     GAS5            2396.315699           0.6012               1
     MEG3             628.060871           0.0000               1
     MIAT             468.775911           0.7830               1
   SNHG12             309.776139           0.7088               0
     HULC             244.536891           2.2822               1
   HOTAIR              32.148565           1.2736               1
HNF1A-AS1               0.000000           2.1306               1
LINC01116               0.000000           0.5312               1

In [29]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("ncrna_platform.db")

# 1) show schema
cols = pd.read_sql_query("PRAGMA table_info(target_scores);", conn)
print("TARGET_SCORES COLUMNS:")
print(cols[["name", "type"]].to_string(index=False))

# 2) inspect tcga values if columns exist
query = """
SELECT
    ncrna_id,
    translational_score,
    expr_mean_tcga_pancan,
    expr_median_tcga_pancan,
    in_tcga_pancan_expr
FROM target_scores
LIMIT 20
"""
try:
    preview = pd.read_sql_query(query, conn)
    print("\nTARGET_SCORES TCGA PREVIEW:")
    print(preview)
except Exception as e:
    print("\nTCGA preview query failed:")
    print(e)

conn.close()

TARGET_SCORES COLUMNS:
                   name type
               score_id TEXT
               ncrna_id TEXT
             disease_id TEXT
             context_id TEXT
        relevance_score REAL
      specificity_score REAL
        mechanism_score REAL
     tractability_score REAL
   human_evidence_score REAL
             risk_score REAL
    translational_score REAL
        confidence_tier TEXT
           top_evidence TEXT
             risk_flags TEXT
recommended_experiments TEXT
          model_version TEXT
            scored_date TEXT

TCGA preview query failed:
Execution failed on sql '
SELECT
    ncrna_id,
    translational_score,
    expr_mean_tcga_pancan,
    expr_median_tcga_pancan,
    in_tcga_pancan_expr
FROM target_scores
LIMIT 20
': no such column: expr_mean_tcga_pancan

In [30]:
import os
import sys
import pandas as pd

os.chdir("/Users/beshoyarmanios/ncrna_platform")
if os.getcwd() not in sys.path:
    sys.path.insert(0, os.getcwd())

from models.features import build_feature_matrix

df = build_feature_matrix()

tcga_cols = [
    "ncrna_id",
    "expr_mean_tcga_pancan",
    "expr_median_tcga_pancan",
    "expr_std_tcga_pancan",
    "expr_min_tcga_pancan",
    "expr_max_tcga_pancan",
    "expr_q1_tcga_pancan",
    "expr_q3_tcga_pancan",
    "expr_iqr_tcga_pancan",
    "expr_prevalence_tcga_pancan",
    "in_tcga_pancan_expr",
]

tcga_update_df = df[tcga_cols].copy()

print(tcga_update_df.to_string(index=False))

✅ Feature matrix: 12 ncRNAs × 72 features
  ncrna_id  expr_mean_tcga_pancan  expr_median_tcga_pancan  expr_std_tcga_pancan  expr_min_tcga_pancan  expr_max_tcga_pancan  expr_q1_tcga_pancan  expr_q3_tcga_pancan  expr_iqr_tcga_pancan  expr_prevalence_tcga_pancan  in_tcga_pancan_expr
LNCRNA_001               0.000000                 0.000000              0.000000              0.000000          0.000000e+00               0.0000             0.000000              0.000000                     0.000000                    0
LNCRNA_002           12035.397508              7605.220000          13908.525749             80.033100          3.269250e+05            3719.1700         15268.700000          11549.530000                     1.000000                    1
LNCRNA_003            4113.415008              2456.990000           5765.734516             41.124700          1.090134e+05            1367.5300          4588.410000           3220.880000                     1.000000                    1
LNCRNA_004             309.776139               246.273000            248.383756              4.250800          3.570240e+03             139.6750           408.543000            268.868000                     1.000000                    1
LNCRNA_005             244.536891                 0.000000           1774.257500             -0.072964          5.305650e+04               0.0000             0.583175              0.583175                     0.400217                    1
LNCRNA_006              32.148565                 3.047550            121.751617             -0.275567          7.937710e+03               0.0000            17.716725             17.716725                     0.716235                    1
LNCRNA_007            2396.315699              1732.370000           2418.685196            148.294000          5.048450e+04            1069.6100          2841.630000           1772.020000                     1.000000                    1
LNCRNA_008               0.000000                 0.000000              0.000000              0.000000          0.000000e+00               0.0000             0.000000              0.000000                     0.000000                    0
LNCRNA_009             468.775911               119.190000           1469.307265             -0.007404          4.565550e+04              49.4279           328.938000            279.510100                     0.999819                    1
LNCRNA_010            4477.996169               369.085378           8418.592223             -0.243921          3.619420e+05               2.3199          6512.070000           6509.750100                     0.896377                    1
LNCRNA_011           16457.563256              1279.110000          88043.125977              0.000000          4.682120e+06             347.3440          4516.680000           4169.336000                     0.999910                    1
LNCRNA_012             628.060871                43.867100           2914.970182              0.000000          6.568050e+04              14.0311           141.191000            127.159900                     0.988798                    1

In [31]:
if "expr_mean_tcga_pancan" in filtered_df.columns:
    filtered_df["TCGA mean"] = filtered_df["expr_mean_tcga_pancan"].apply(lambda x: round(safe_float(x), 3))
else:
    filtered_df["TCGA mean"] = 0.0

NameError: name 'filtered_df' is not defined

In [32]:
import os
import sys
import sqlite3
import pandas as pd

os.chdir("/Users/beshoyarmanios/ncrna_platform")
if os.getcwd() not in sys.path:
    sys.path.insert(0, os.getcwd())

from models.features import build_feature_matrix

df = build_feature_matrix()

print("Feature matrix shape:", df.shape)
print("TCGA cols:", [c for c in df.columns if "tcga" in c.lower()])

tcga_cols = [
    "ncrna_id",
    "symbol",
    "expr_mean_tcga_pancan",
    "expr_median_tcga_pancan",
    "expr_std_tcga_pancan",
    "expr_min_tcga_pancan",
    "expr_max_tcga_pancan",
    "expr_q1_tcga_pancan",
    "expr_q3_tcga_pancan",
    "expr_iqr_tcga_pancan",
    "expr_prevalence_tcga_pancan",
    "in_tcga_pancan_expr",
]

tcga_update_df = df[tcga_cols].copy()
print(tcga_update_df)

✅ Feature matrix: 12 ncRNAs × 72 features
Feature matrix shape: (12, 72)
TCGA cols: ['expr_mean_tcga_pancan', 'expr_median_tcga_pancan', 'expr_std_tcga_pancan', 'expr_min_tcga_pancan', 'expr_max_tcga_pancan', 'expr_q1_tcga_pancan', 'expr_q3_tcga_pancan', 'expr_iqr_tcga_pancan', 'expr_prevalence_tcga_pancan', 'in_tcga_pancan_expr']
      ncrna_id     symbol  expr_mean_tcga_pancan  expr_median_tcga_pancan  \
0   LNCRNA_001  HNF1A-AS1               0.000000                 0.000000
1   LNCRNA_002      NEAT1           12035.397508              7605.220000
2   LNCRNA_003     MALAT1            4113.415008              2456.990000
3   LNCRNA_004     SNHG12             309.776139               246.273000
4   LNCRNA_005       HULC             244.536891                 0.000000
5   LNCRNA_006     HOTAIR              32.148565                 3.047550
6   LNCRNA_007       GAS5            2396.315699              1732.370000
7   LNCRNA_008  LINC01116               0.000000                 0.000000
8   LNCRNA_009       MIAT             468.775911               119.190000
9   LNCRNA_010       XIST            4477.996169               369.085378
10  LNCRNA_011        H19           16457.563256              1279.110000
11  LNCRNA_012       MEG3             628.060871                43.867100

    expr_std_tcga_pancan  expr_min_tcga_pancan  expr_max_tcga_pancan  \
0               0.000000              0.000000          0.000000e+00
1           13908.525749             80.033100          3.269250e+05
2            5765.734516             41.124700          1.090134e+05
3             248.383756              4.250800          3.570240e+03
4            1774.257500             -0.072964          5.305650e+04
5             121.751617             -0.275567          7.937710e+03
6            2418.685196            148.294000          5.048450e+04
7               0.000000              0.000000          0.000000e+00
8            1469.307265             -0.007404          4.565550e+04
9            8418.592223             -0.243921          3.619420e+05
10          88043.125977              0.000000          4.682120e+06
11           2914.970182              0.000000          6.568050e+04

    expr_q1_tcga_pancan  expr_q3_tcga_pancan  expr_iqr_tcga_pancan  \
0                0.0000             0.000000              0.000000
1             3719.1700         15268.700000          11549.530000
2             1367.5300          4588.410000           3220.880000
3              139.6750           408.543000            268.868000
4                0.0000             0.583175              0.583175
5                0.0000            17.716725             17.716725
6             1069.6100          2841.630000           1772.020000
7                0.0000             0.000000              0.000000
8               49.4279           328.938000            279.510100
9                2.3199          6512.070000           6509.750100
10             347.3440          4516.680000           4169.336000
11              14.0311           141.191000            127.159900

    expr_prevalence_tcga_pancan  in_tcga_pancan_expr
0                      0.000000                    0
1                      1.000000                    1
2                      1.000000                    1
3                      1.000000                    1
4                      0.400217                    1
5                      0.716235                    1
6                      1.000000                    1
7                      0.000000                    0
8                      0.999819                    1
9                      0.896377                    1
10                     0.999910                    1
11                     0.988798                    1

In [33]:
import sqlite3
import pandas as pd

tcga_cols = [
    "expr_mean_tcga_pancan",
    "expr_median_tcga_pancan",
    "expr_std_tcga_pancan",
    "expr_min_tcga_pancan",
    "expr_max_tcga_pancan",
    "expr_q1_tcga_pancan",
    "expr_q3_tcga_pancan",
    "expr_iqr_tcga_pancan",
    "expr_prevalence_tcga_pancan",
    "in_tcga_pancan_expr",
]

conn = sqlite3.connect("ncrna_platform.db")
cur = conn.cursor()

existing_cols = pd.read_sql_query("PRAGMA table_info(target_scores);", conn)["name"].tolist()

for col in tcga_cols:
    if col not in existing_cols:
        col_type = "INTEGER" if col == "in_tcga_pancan_expr" else "REAL"
        cur.execute(f"ALTER TABLE target_scores ADD COLUMN {col} {col_type}")

conn.commit()

update_df = df[["ncrna_id"] + tcga_cols].copy()

for _, r in update_df.iterrows():
    cur.execute(
        """
        UPDATE target_scores
        SET expr_mean_tcga_pancan = ?,
            expr_median_tcga_pancan = ?,
            expr_std_tcga_pancan = ?,
            expr_min_tcga_pancan = ?,
            expr_max_tcga_pancan = ?,
            expr_q1_tcga_pancan = ?,
            expr_q3_tcga_pancan = ?,
            expr_iqr_tcga_pancan = ?,
            expr_prevalence_tcga_pancan = ?,
            in_tcga_pancan_expr = ?
        WHERE ncrna_id = ?
        """,
        (
            float(r["expr_mean_tcga_pancan"]),
            float(r["expr_median_tcga_pancan"]),
            float(r["expr_std_tcga_pancan"]),
            float(r["expr_min_tcga_pancan"]),
            float(r["expr_max_tcga_pancan"]),
            float(r["expr_q1_tcga_pancan"]),
            float(r["expr_q3_tcga_pancan"]),
            float(r["expr_iqr_tcga_pancan"]),
            float(r["expr_prevalence_tcga_pancan"]),
            int(r["in_tcga_pancan_expr"]),
            r["ncrna_id"],
        ),
    )

conn.commit()

check = pd.read_sql_query(
    """
    SELECT
        ncrna_id,
        expr_mean_tcga_pancan,
        expr_median_tcga_pancan,
        in_tcga_pancan_expr
    FROM target_scores
    ORDER BY ncrna_id
    """,
    conn,
)

conn.close()

print(check.to_string(index=False))

  ncrna_id  expr_mean_tcga_pancan  expr_median_tcga_pancan  in_tcga_pancan_expr
LNCRNA_001               0.000000                 0.000000                    0
LNCRNA_002           12035.397508              7605.220000                    1
LNCRNA_003            4113.415008              2456.990000                    1
LNCRNA_004             309.776139               246.273000                    1
LNCRNA_005             244.536891                 0.000000                    1
LNCRNA_006              32.148565                 3.047550                    1
LNCRNA_007            2396.315699              1732.370000                    1
LNCRNA_008               0.000000                 0.000000                    0
LNCRNA_009             468.775911               119.190000                    1
LNCRNA_010            4477.996169               369.085378                    1
LNCRNA_011           16457.563256              1279.110000                    1
LNCRNA_012             628.060871                43.867100                    1

In [34]:
from pathlib import Path

p = Path("run_pipeline.py")
text = p.read_text()

keywords = [
    "target_scores",
    "expr_mean_tcga_pancan",
    "expr_median_tcga_pancan",
    "in_tcga_pancan_expr",
    "build_feature_matrix",
    "to_sql",
    "sqlite3",
]

print("run_pipeline.py exists:", p.exists())
print("\nKeyword check:")
for k in keywords:
    print(f"{k}: {k in text}")

run_pipeline.py exists: True

Keyword check:
target_scores: False
expr_mean_tcga_pancan: False
expr_median_tcga_pancan: False
in_tcga_pancan_expr: False
build_feature_matrix: False
to_sql: False
sqlite3: False

In [35]:
from pathlib import Path

p = Path("run_pipeline.py")
text = p.read_text()

print(text[:4000])

"""
ncRNA Target Intelligence Platform — One-command launcher.
Run: python run_platform.py
"""

from schema import create_database, seed_liver_masld_data
from scoring import run_scoring_pipeline
from knowledge_graph import build_knowledge_graph, extract_graph_features, predict_novel_associations

DB_PATH = "ncrna_platform.db"

print("=" * 60)
print("  ncRNA Target Intelligence Platform — Setup & Launch")
print("=" * 60)

print("\n[1/3] Building database and seeding MASLD/liver data...")
conn = create_database(DB_PATH)
seed_liver_masld_data(conn)
conn.close()

print("\n[2/3] Running translational scoring pipeline...")
scored_df, model_out = run_scoring_pipeline(DB_PATH)

print("\n[3/3] Building knowledge graph...")
G = build_knowledge_graph(DB_PATH)
ncrna_ids = [n for n, d in G.nodes(data=True) if d.get("node_type") == "ncRNA"]
disease_ids = [n for n, d in G.nodes(data=True) if d.get("node_type") == "Disease"]

graph_feats = extract_graph_features(G, ncrna_ids)
novel_links = predict_novel_associations(G, ncrna_ids, disease_ids, top_k=5)

print("\n── Novel Predicted Associations ──")
print(novel_links.to_string(index=False))

print("\n" + "=" * 60)
print("✅ Setup complete!")
print("Launch dashboard: streamlit run dashboard.py")
print("Database: ncrna_platform.db")
print("=" * 60)

In [36]:
from pathlib import Path

for fname in ["scoring.py", "schema.py", "knowledge_graph.py"]:
    p = Path(fname)
    print("\n" + "="*80)
    print(fname, "exists:", p.exists())
    if p.exists():
        text = p.read_text()
        print(text[:2500])

================================================================================
scoring.py exists: False

================================================================================
schema.py exists: False

================================================================================
knowledge_graph.py exists: False

In [37]:
from pathlib import Path
import os

root = Path(".")
matches = []

for path in root.rglob("*.py"):
    try:
        text = path.read_text()
    except Exception:
        continue
    for term in ["target_scores", "sqlite3", "to_sql", "create_database", "run_scoring_pipeline"]:
        if term in text:
            matches.append((str(path), term))

for m in matches:
    print(m)

('run_pipeline.py', 'create_database')
('run_pipeline.py', 'run_scoring_pipeline')
('app/dashboard.py', 'target_scores')
('app/dashboard.py', 'sqlite3')
('etl/ingest_literature.py', 'sqlite3')
('models/knowledge_graph.py', 'sqlite3')
('models/scoring.py', 'target_scores')
('models/scoring.py', 'sqlite3')
('models/scoring.py', 'run_scoring_pipeline')
('models/features.py', 'sqlite3')
('scripts/patch_ncrna_master.py', 'sqlite3')
('scripts/patch_ncrna_master.py', 'to_sql')
('scripts/validate_db.py', 'target_scores')
('scripts/validate_db.py', 'sqlite3')
('scripts/benchmark_v01.py', 'target_scores')
('scripts/benchmark_v01.py', 'sqlite3')
('scripts/reconcile_symbols.py', 'target_scores')
('scripts/reconcile_symbols.py', 'sqlite3')
('db/schema.py', 'target_scores')
('db/schema.py', 'sqlite3')
('db/schema.py', 'create_database')
('.ipynb_checkpoints/run_pipeline-checkpoint.py', 'create_database')
('.ipynb_checkpoints/run_pipeline-checkpoint.py', 'run_scoring_pipeline')
('db/.ipynb_checkpoints/schema-checkpoint.py', 'target_scores')
('db/.ipynb_checkpoints/schema-checkpoint.py', 'sqlite3')
('db/.ipynb_checkpoints/schema-checkpoint.py', 'create_database')
('scripts/.ipynb_checkpoints/reconcile_symbols-checkpoint.py', 'target_scores')
('scripts/.ipynb_checkpoints/reconcile_symbols-checkpoint.py', 'sqlite3')
('scripts/.ipynb_checkpoints/validate_db-checkpoint.py', 'target_scores')
('scripts/.ipynb_checkpoints/validate_db-checkpoint.py', 'sqlite3')
('scripts/.ipynb_checkpoints/benchmark_v01-checkpoint.py', 'target_scores')
('scripts/.ipynb_checkpoints/benchmark_v01-checkpoint.py', 'sqlite3')
('scripts/.ipynb_checkpoints/patch_ncrna_master-checkpoint.py', 'sqlite3')
('scripts/.ipynb_checkpoints/patch_ncrna_master-checkpoint.py', 'to_sql')
('models/.ipynb_checkpoints/knowledge_graph-checkpoint.py', 'sqlite3')
('models/.ipynb_checkpoints/features-checkpoint.py', 'sqlite3')
('models/.ipynb_checkpoints/scoring-checkpoint.py', 'target_scores')
('models/.ipynb_checkpoints/scoring-checkpoint.py', 'sqlite3')
('models/.ipynb_checkpoints/scoring-checkpoint.py', 'run_scoring_pipeline')
('etl/.ipynb_checkpoints/ingest_literature-checkpoint.py', 'sqlite3')
('app/.ipynb_checkpoints/dashboard-checkpoint.py', 'target_scores')
('app/.ipynb_checkpoints/dashboard-checkpoint.py', 'sqlite3')

In [38]:
from pathlib import Path

for fname in ["models/scoring.py", "db/schema.py"]:
    p = Path(fname)
    print("\n" + "=" * 100)
    print(fname)
    print("=" * 100)
    print(p.read_text()[:5000])

====================================================================================================
models/scoring.py
====================================================================================================
"""
ncRNA Target Intelligence Platform — Translational Scoring Engine
Phase 2: curated target evidence integrated
"""

import sqlite3
import json
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score

try:
    import xgboost as xgb
    HAS_XGB = True
except Exception as e:
    xgb = None
    HAS_XGB = False
    print(f"⚠️ XGBoost unavailable; using GradientBoostingRegressor instead. Reason: {e}")

from models.features import build_feature_matrix

SCORE_WEIGHTS = {
    "relevance": 0.22,
    "specificity": 0.12,
    "mechanism": 0.18,
    "tractability": 0.12,
    "human_evidence": 0.16,
    "curated": 0.15,
    "risk": 0.05,
}

RELEVANCE_FEATURES = [
    "mean_abs_log2fc",
    "sig_rate",
    "de_consistency",
]

SPECIFICITY_FEATURES = [
    "mean_tau",
    "log_tpm_disease",
]

MECHANISM_FEATURES = [
    "n_perturbation_studies",
    "mean_pert_effect",
    "n_high_conf_perts",
    "n_pathways",
    "max_hub_correlation",
]

TRACTABILITY_FEATURES = [
    "modality_breadth",
    "aso_accessible",
    "sirna_compatible",
    "crispr_feasible",
]

HUMAN_EVIDENCE_FEATURES = [
    "n_clinical_studies",
    "mean_clinical_r",
    "n_sig_clinical",
    "n_prognostic",
    "mean_lit_confidence",
    "n_unique_papers",
]

CURATED_FEATURES = [
    "curated_exists",
    "curated_tier_score",
    "curated_hcc_flag",
    "curated_masld_flag",
    "curated_fibrosis_flag",
    "curated_mash_flag",
]

RISK_FEATURES = [
    "risk_ubiquitous",
    "risk_contradictory_lit",
    "risk_high_isoforms",
    "curated_contradiction_flag",
]

ALL_FEATURE_COLS = (
    RELEVANCE_FEATURES
    + SPECIFICITY_FEATURES
    + MECHANISM_FEATURES
    + TRACTABILITY_FEATURES
    + HUMAN_EVIDENCE_FEATURES
    + CURATED_FEATURES
    + RISK_FEATURES
)


def compute_component_score(df: pd.DataFrame, feature_cols: list) -> pd.Series:
    sub = df[feature_cols].copy().fillna(0)

    if sub.shape[1] == 0:
        return pd.Series(0.0, index=df.index)

    scaler = MinMaxScaler()
    scaled = scaler.fit_transform(sub)
    return pd.Series(scaled.mean(axis=1), index=df.index)


def compute_risk_penalty(df: pd.DataFrame) -> pd.Series:
    risk_raw = compute_component_score(df, RISK_FEATURES)
    return 1.0 - risk_raw


def compute_translational_scores(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy().fillna(0)

    df["relevance_score"] = compute_component_score(df, RELEVANCE_FEATURES)
    df["specificity_score"] = compute_component_score(df, SPECIFICITY_FEATURES)
    df["mechanism_score"] = compute_component_score(df, MECHANISM_FEATURES)
    df["tractability_score"] = compute_component_score(df, TRACTABILITY_FEATURES)
    df["human_evidence_score"] = compute_component_score(df, HUMAN_EVIDENCE_FEATURES)
    df["curated_score"] = compute_component_score(df, CURATED_FEATURES)
    df["risk_score"] = compute_risk_penalty(df)

    df["translational_score"] = (
        SCORE_WEIGHTS["relevance"] * df["relevance_score"]
        + SCORE_WEIGHTS["specificity"] * df["specificity_score"]
        + SCORE_WEIGHTS["mechanism"] * df["mechanism_score"]
        + SCORE_WEIGHTS["tractability"] * df["tractability_score"]
        + SCORE_WEIGHTS["human_evidence"] * df["human_evidence_score"]
        + SCORE_WEIGHTS["curated"] * df["curated_score"]
        + SCORE_WEIGHTS["risk"] * df["risk_score"]
    )

    df["translational_score"] = df["translational_score"].clip(0, 1)

    def assign_tier(score):
        if score >= 0.68:
            return "Tier 1 — High Confidence"
        elif score >= 0.42:
            return "Tier 2 — Moderate Confidence"
        return "Tier 3 — Exploratory"

    df["confidence_tier"] = df["translational_score"].apply(assign_tier)
    return df.sort_values("translational_score", ascending=False)


def train_ranking_model(df: pd.DataFrame, label_col: str = "translational_score") -> dict:
    feature_cols = [c for c in ALL_FEATURE_COLS if c in df.columns]
    X = df[feature_cols].fillna(0).values
    y = df[label_col].values

    if HAS_XGB and xgb is not None:
        try:
            model = xgb.XGBRegressor(
                n_estimators=200,
                max_depth=4,
                learning_rate=0.05,
                subsample=0.8,
                colsample_bytree=0.8,
                reg_alpha=0.1,
                reg_lambda=1.0,
                random_state=42,
                verbosity=0
            )
            model_name = "XGBoost"
        except Exception:
            model = GradientBoostingRegressor(
                n_estimators=200,
                learning_rate=0.05,
                subsample=0.8,
                random_state=42
            )
            model_name = "GradientBoostingRegressor"
    else:
        model = GradientBoostingRegressor(
            n_estimators=200,
            learning_rate=0.05,
            subsample=0.8,
            random_state=42
        )
        model_name = "GradientBoosti

====================================================================================================
db/schema.py
====================================================================================================
"""
ncRNA Target Intelligence Platform — Data Schema & Seed Data
Phase 1 Wedge: Liver MASLD/MASH → Fibrosis/HCC
"""

import sqlite3
import json
import numpy as np
import random

random.seed(42)
np.random.seed(42)


def create_database(db_path="ncrna_platform.db"):
    conn = sqlite3.connect(db_path)
    c = conn.cursor()

    c.executescript("""
    CREATE TABLE IF NOT EXISTS ncrna_master (
        ncrna_id            TEXT PRIMARY KEY,
        symbol              TEXT,
        aliases             TEXT,
        biotype             TEXT,
        chrom               TEXT,
        start_pos           INTEGER,
        end_pos             INTEGER,
        strand              TEXT,
        transcript_count    INTEGER,
        conservation_score  REAL,
        ensembl_id          TEXT,
        added_date          TEXT DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS disease_context (
        disease_id      TEXT PRIMARY KEY,
        disease_name    TEXT NOT NULL,
        doid            TEXT,
        mondo_id        TEXT,
        mesh_id         TEXT,
        stage           TEXT,
        subtype         TEXT,
        species         TEXT DEFAULT "Homo sapiens",
        cohort_size     INTEGER,
        data_source     TEXT,
        added_date      TEXT DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS tissue_cell_context (
        context_id      TEXT PRIMARY KEY,
        tissue          TEXT NOT NULL,
        cell_type       TEXT,
        cell_state      TEXT,
        platform        TEXT,
        atlas_source    TEXT,
        sample_count    INTEGER,
        added_date      TEXT DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS expression_evidence (
        evidence_id         TEXT PRIMARY KEY,
        ncrna_id            TEXT REFERENCES ncrna_master(ncrna_id),
        disease_id          TEXT REFERENCES disease_context(disease_id),
        context_id          TEXT REFERENCES tissue_cell_context(context_id),
        log2fc              REAL,
        pvalue              REAL,
        padj                REAL,
        basemean            REAL,
        tpm_disease         REAL,
        tpm_healthy         REAL,
        specificity_tau     REAL,
        direction           TEXT,
        dataset_id          TEXT,
        added_date          TEXT DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS pathway_links (
        link_id             TEXT PRIMARY KEY,
        ncrna_id            TEXT REFERENCES ncrna_master(ncrna_id),
        pathway_name        TEXT,
        pathway_db          TEXT,
        pathway_id          TEXT,
        enrichment_pval     REAL,
        enrichment_fdr      REAL,
        coexp_module        TEXT,
        hub_gene            TEXT,
        pearson_r           REAL,
        added_date          TEXT DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS perturbation_evidence (
        pert_id             TEXT PRIMARY KEY,
        ncrna_id            TEXT REFERENCES ncrna_master(ncrna_id),
        perturbation_type   TEXT,
        target_gene_effect  TEXT,
        effect_size         REAL,
        phenotype           TEXT,
        cell_model          TEXT,
        species             TEXT DEFAULT "Homo sapiens",
        pubmed_id           TEXT,
        confidence          TEXT,
        added_date          TEXT DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS clinical_links (
        clin_id             TEXT PRIMARY KEY,
        ncrna_id            TEXT REFERENCES ncrna_master(ncrna_id),
        disease_id          TEXT REFERENCES disease_context(disease_id),
        clinical_metric     TEXT,
        correlation_r       REAL,
        pvalue              REAL,
        biomarker_type      TEXT,
        sample_type         TEXT,
        cohort_id           TEXT,
        pubmed_id           TEXT,
        added_date          TEXT DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS tractability_features (
        tract_id                    TEXT PRIMARY KEY,
        ncrna_id                    TEXT REFERENCES ncrna_master(ncrna_id),
        localization                TEXT,
        isoform_count               INTEGER,
        gc_content                  REAL,
        secondary_structure_score   REAL,
        aso_accessible              INTEGER,
        sirna_compatible            INTEGER,
        small_mol_bindable          INTEGER,
        crispr_feasible             INTEGER,
        best_modality               TEXT,
        added_date                  TEXT DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS literature_evidence (
        lit_id              TEXT PRIMARY KEY,
        ncrna_id            TEXT REFERENCES ncrna_master(ncrna_id),
        disease_id          TEXT REFERENCES disease_context(disease_id),
        statement           TEXT,
        direction           TEXT,
        confidence_score    REAL,
        pubmed_id           TEXT,
        journal             TEXT,
        yea

In [39]:
from pathlib import Path

text = Path("models/scoring.py").read_text()

for key in ["INSERT INTO target_scores", "to_sql", "target_scores", "run_scoring_pipeline", "CREATE TABLE", "recommended_experiments"]:
    print("\n" + "="*40)
    print(key)
    idx = text.find(key)
    print("index:", idx)
    if idx != -1:
        start = max(0, idx - 600)
        end = min(len(text), idx + 2200)
        print(text[start:end])

========================================
INSERT INTO target_scores
index: -1

========================================
to_sql
index: -1

========================================
target_scores
index: 8349
plicate oligo design")
    if row.get("curated_contradiction_flag", 0):
        flags.append("Manual curation flagged this target as contradictory/context-dependent")
    if row.get("curated_exists", 0) == 0:
        flags.append("No curated liver-disease evidence currently linked")

    return flags if flags else ["No major risk flags identified"]


def save_scores_to_db(
    scored_df: pd.DataFrame,
    db_path="ncrna_platform.db",
    disease_id="DIS_001",
    context_id="CTX_001"
):
    conn = sqlite3.connect(db_path)
    c = conn.cursor()

    c.execute("""
    CREATE TABLE IF NOT EXISTS target_scores (
        score_id TEXT PRIMARY KEY,
        ncrna_id TEXT,
        disease_id TEXT,
        context_id TEXT,
        relevance_score REAL,
        specificity_score REAL,
        mechanism_score REAL,
        tractability_score REAL,
        human_evidence_score REAL,
        risk_score REAL,
        translational_score REAL,
        confidence_tier TEXT,
        top_evidence TEXT,
        risk_flags TEXT,
        recommended_experiments TEXT,
        model_version TEXT
    )
    """)

    for _, row in scored_df.iterrows():
        nid = row["ncrna_id"]
        exps = recommend_experiments(row)
        flags = build_risk_flags(row)

        top_ev = []
        if row.get("curated_exists", 0):
            top_ev.append(f"Curated liver evidence tier score = {row.get('curated_tier_score', 0):.2f}")
        if row.get("mean_abs_log2fc", 0) > 0:
            top_ev.append(f"Mean |log2FC| = {row['mean_abs_log2fc']:.2f}")
        if row.get("mean_clinical_r", 0) > 0:
            top_ev.append(f"Clinical correlation r = {row['mean_clinical_r']:.2f}")
        if row.get("n_high_conf_perts", 0) > 0:
            top_ev.append(f"{int(row['n_high_conf_perts'])} high-confidence perturbation studies")

        if not top_ev:
            top_ev = ["Limited evidence available"]

        c.execute("""
            INSERT OR REPLACE INTO target_scores
            (
                score_id, ncrna_id, disease_id, context_id,
                relevance_score, specificity_score, mechanism_score,
                tractability_score, human_evidence_score, risk_score,
                translational_score, confidence_tier,
                top_evidence, risk_flags, recommended_experiments,
                model_version
            )
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"v2.0")
        """, (
            f"SCR_{nid}_{disease_id}",
            nid,
            disease_id,
            context_id,
            round(float(row.get("relevance_score", 0)), 4),
            round(float(row.get("specificity_score", 0)), 4),
            round(float(row.get("mechanism_score", 0)), 4),
            round(float(row.get("tractability_score", 0)), 4),
            round(float(row.get

========================================
run_scoring_pipeline
index: 10970
ificity_score", 0)), 4),
            round(float(row.get("mechanism_score", 0)), 4),
            round(float(row.get("tractability_score", 0)), 4),
            round(float(row.get("human_evidence_score", 0)), 4),
            round(float(row.get("risk_score", 0)), 4),
            round(float(row.get("translational_score", 0)), 4),
            row.get("confidence_tier", "Tier 3 — Exploratory"),
            json.dumps(top_ev),
            json.dumps(flags),
            json.dumps(exps),
        ))

    conn.commit()
    conn.close()
    print(f"✅ {len(scored_df)} scores saved to database")


def run_scoring_pipeline(db_path="ncrna_platform.db", disease_id="DIS_001", context_id="CTX_001"):
    print("\n── ncRNA Target Intelligence Platform ──")
    print(f"   Disease: {disease_id}  |  Context: {context_id}\n")

    feat_df = build_feature_matrix(db_path, disease_id, context_id)
    scored_df = compute_translational_scores(feat_df)
    model_out = train_ranking_model(scored_df)
    save_scores_to_db(scored_df, db_path, disease_id, context_id)

    print("\n── Top 10 Ranked ncRNA Targets ──")
    display_cols = [
        "symbol",
        "translational_score",
        "confidence_tier",
        "curated_tier_score",
        "relevance_score",
        "mechanism_score",
        "human_evidence_score",
    ]
    print(scored_df[display_cols].head(10).to_string(index=False))
    return scored_df, model_out


if __name__ == "__main__":
    scored_df, model_out = run_scoring_pipeline()

========================================
CREATE TABLE
index: 8322
 isoform complexity may complicate oligo design")
    if row.get("curated_contradiction_flag", 0):
        flags.append("Manual curation flagged this target as contradictory/context-dependent")
    if row.get("curated_exists", 0) == 0:
        flags.append("No curated liver-disease evidence currently linked")

    return flags if flags else ["No major risk flags identified"]


def save_scores_to_db(
    scored_df: pd.DataFrame,
    db_path="ncrna_platform.db",
    disease_id="DIS_001",
    context_id="CTX_001"
):
    conn = sqlite3.connect(db_path)
    c = conn.cursor()

    c.execute("""
    CREATE TABLE IF NOT EXISTS target_scores (
        score_id TEXT PRIMARY KEY,
        ncrna_id TEXT,
        disease_id TEXT,
        context_id TEXT,
        relevance_score REAL,
        specificity_score REAL,
        mechanism_score REAL,
        tractability_score REAL,
        human_evidence_score REAL,
        risk_score REAL,
        translational_score REAL,
        confidence_tier TEXT,
        top_evidence TEXT,
        risk_flags TEXT,
        recommended_experiments TEXT,
        model_version TEXT
    )
    """)

    for _, row in scored_df.iterrows():
        nid = row["ncrna_id"]
        exps = recommend_experiments(row)
        flags = build_risk_flags(row)

        top_ev = []
        if row.get("curated_exists", 0):
            top_ev.append(f"Curated liver evidence tier score = {row.get('curated_tier_score', 0):.2f}")
        if row.get("mean_abs_log2fc", 0) > 0:
            top_ev.append(f"Mean |log2FC| = {row['mean_abs_log2fc']:.2f}")
        if row.get("mean_clinical_r", 0) > 0:
            top_ev.append(f"Clinical correlation r = {row['mean_clinical_r']:.2f}")
        if row.get("n_high_conf_perts", 0) > 0:
            top_ev.append(f"{int(row['n_high_conf_perts'])} high-confidence perturbation studies")

        if not top_ev:
            top_ev = ["Limited evidence available"]

        c.execute("""
            INSERT OR REPLACE INTO target_scores
            (
                score_id, ncrna_id, disease_id, context_id,
                relevance_score, specificity_score, mechanism_score,
                tractability_score, human_evidence_score, risk_score,
                translational_score, confidence_tier,
                top_evidence, risk_flags, recommended_experiments,
                model_version
            )
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"v2.0")
        """, (
            f"SCR_{nid}_{disease_id}",
            nid,
            disease_id,
            context_id,
            round(float(row.get("relevance_score", 0)), 4),
            round(float(row.get("specificity_score", 0)), 4),
            round(float(row.get("mechanism_score", 0)), 4),
            round(float(row.get("tractability_score", 0)), 4),


========================================
recommended_experiments
index: 8782
db",
    disease_id="DIS_001",
    context_id="CTX_001"
):
    conn = sqlite3.connect(db_path)
    c = conn.cursor()

    c.execute("""
    CREATE TABLE IF NOT EXISTS target_scores (
        score_id TEXT PRIMARY KEY,
        ncrna_id TEXT,
        disease_id TEXT,
        context_id TEXT,
        relevance_score REAL,
        specificity_score REAL,
        mechanism_score REAL,
        tractability_score REAL,
        human_evidence_score REAL,
        risk_score REAL,
        translational_score REAL,
        confidence_tier TEXT,
        top_evidence TEXT,
        risk_flags TEXT,
        recommended_experiments TEXT,
        model_version TEXT
    )
    """)

    for _, row in scored_df.iterrows():
        nid = row["ncrna_id"]
        exps = recommend_experiments(row)
        flags = build_risk_flags(row)

        top_ev = []
        if row.get("curated_exists", 0):
            top_ev.append(f"Curated liver evidence tier score = {row.get('curated_tier_score', 0):.2f}")
        if row.get("mean_abs_log2fc", 0) > 0:
            top_ev.append(f"Mean |log2FC| = {row['mean_abs_log2fc']:.2f}")
        if row.get("mean_clinical_r", 0) > 0:
            top_ev.append(f"Clinical correlation r = {row['mean_clinical_r']:.2f}")
        if row.get("n_high_conf_perts", 0) > 0:
            top_ev.append(f"{int(row['n_high_conf_perts'])} high-confidence perturbation studies")

        if not top_ev:
            top_ev = ["Limited evidence available"]

        c.execute("""
            INSERT OR REPLACE INTO target_scores
            (
                score_id, ncrna_id, disease_id, context_id,
                relevance_score, specificity_score, mechanism_score,
                tractability_score, human_evidence_score, risk_score,
                translational_score, confidence_tier,
                top_evidence, risk_flags, recommended_experiments,
                model_version
            )
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"v2.0")
        """, (
            f"SCR_{nid}_{disease_id}",
            nid,
            disease_id,
            context_id,
            round(float(row.get("relevance_score", 0)), 4),
            round(float(row.get("specificity_score", 0)), 4),
            round(float(row.get("mechanism_score", 0)), 4),
            round(float(row.get("tractability_score", 0)), 4),
            round(float(row.get("human_evidence_score", 0)), 4),
            round(float(row.get("risk_score", 0)), 4),
            round(float(row.get("translational_score", 0)), 4),
            row.get("confidence_tier", "Tier 3 — Exploratory"),
            json.dumps(top_ev),
            json.dumps(flags),
            json.dumps(exps),
        ))

    conn.commit()
    conn.close()
    print(f"✅ {len(scored_df)} scores saved to database")


def run_scoring_

In [40]:
from pathlib import Path

text = Path("models/scoring.py").read_text()
start = text.find("def save_scores_to_db(")
end = text.find("def run_scoring_pipeline(")

print(text[start:end])

def save_scores_to_db(
    scored_df: pd.DataFrame,
    db_path="ncrna_platform.db",
    disease_id="DIS_001",
    context_id="CTX_001"
):
    conn = sqlite3.connect(db_path)
    c = conn.cursor()

    c.execute("""
    CREATE TABLE IF NOT EXISTS target_scores (
        score_id TEXT PRIMARY KEY,
        ncrna_id TEXT,
        disease_id TEXT,
        context_id TEXT,
        relevance_score REAL,
        specificity_score REAL,
        mechanism_score REAL,
        tractability_score REAL,
        human_evidence_score REAL,
        risk_score REAL,
        translational_score REAL,
        confidence_tier TEXT,
        top_evidence TEXT,
        risk_flags TEXT,
        recommended_experiments TEXT,
        model_version TEXT
    )
    """)

    for _, row in scored_df.iterrows():
        nid = row["ncrna_id"]
        exps = recommend_experiments(row)
        flags = build_risk_flags(row)

        top_ev = []
        if row.get("curated_exists", 0):
            top_ev.append(f"Curated liver evidence tier score = {row.get('curated_tier_score', 0):.2f}")
        if row.get("mean_abs_log2fc", 0) > 0:
            top_ev.append(f"Mean |log2FC| = {row['mean_abs_log2fc']:.2f}")
        if row.get("mean_clinical_r", 0) > 0:
            top_ev.append(f"Clinical correlation r = {row['mean_clinical_r']:.2f}")
        if row.get("n_high_conf_perts", 0) > 0:
            top_ev.append(f"{int(row['n_high_conf_perts'])} high-confidence perturbation studies")

        if not top_ev:
            top_ev = ["Limited evidence available"]

        c.execute("""
            INSERT OR REPLACE INTO target_scores
            (
                score_id, ncrna_id, disease_id, context_id,
                relevance_score, specificity_score, mechanism_score,
                tractability_score, human_evidence_score, risk_score,
                translational_score, confidence_tier,
                top_evidence, risk_flags, recommended_experiments,
                model_version
            )
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"v2.0")
        """, (
            f"SCR_{nid}_{disease_id}",
            nid,
            disease_id,
            context_id,
            round(float(row.get("relevance_score", 0)), 4),
            round(float(row.get("specificity_score", 0)), 4),
            round(float(row.get("mechanism_score", 0)), 4),
            round(float(row.get("tractability_score", 0)), 4),
            round(float(row.get("human_evidence_score", 0)), 4),
            round(float(row.get("risk_score", 0)), 4),
            round(float(row.get("translational_score", 0)), 4),
            row.get("confidence_tier", "Tier 3 — Exploratory"),
            json.dumps(top_ev),
            json.dumps(flags),
            json.dumps(exps),
        ))

    conn.commit()
    conn.close()
    print(f"✅ {len(scored_df)} scores saved to database")

In [41]:
from models.scoring import run_scoring_pipeline
scored_df, model_out = run_scoring_pipeline("ncrna_platform.db", "DIS_001", "CTX_001")
print(scored_df[["symbol", "translational_score", "expr_mean_tcga_pancan", "in_tcga_pancan_expr"]].to_string(index=False))

── ncRNA Target Intelligence Platform ──
   Disease: DIS_001  |  Context: CTX_001

✅ Feature matrix: 12 ncRNAs × 72 features
✅ Model trained with XGBoost | CV R² = -547.201 ± 1071.783
✅ 12 scores saved to database

── Top 10 Ranked ncRNA Targets ──
   symbol  translational_score              confidence_tier  curated_tier_score  relevance_score  mechanism_score  human_evidence_score  expr_mean_tcga_pancan
HNF1A-AS1             0.850372     Tier 1 — High Confidence                1.00         0.811191         0.948864              0.987118               0.000000
     HULC             0.669504 Tier 2 — Moderate Confidence                1.00         0.666667         0.454545              0.626398             244.536891
   HOTAIR             0.649897 Tier 2 — Moderate Confidence                1.00         0.452686         0.800000              0.666667              32.148565
    NEAT1             0.626224 Tier 2 — Moderate Confidence                1.00         0.586636         0.704545              0.442555           12035.397508
     GAS5             0.554820 Tier 2 — Moderate Confidence                0.66         0.387810         0.481061              0.413969            2396.315699
   MALAT1             0.503890 Tier 2 — Moderate Confidence                1.00         0.392455         0.453030              0.228022            4113.415008
     MIAT             0.462746 Tier 2 — Moderate Confidence                0.33         0.647697         0.175000              0.000000             468.775911
   SNHG12             0.408485         Tier 3 — Exploratory                0.00         0.636859         0.000000              0.000000             309.776139
     XIST             0.316096         Tier 3 — Exploratory                0.00         0.392922         0.000000              0.000000            4477.996169
LINC01116             0.268514         Tier 3 — Exploratory                0.33         0.210919         0.000000              0.160256               0.000000
   symbol  translational_score  expr_mean_tcga_pancan  in_tcga_pancan_expr
HNF1A-AS1             0.850372               0.000000                    0
     HULC             0.669504             244.536891                    1
   HOTAIR             0.649897              32.148565                    1
    NEAT1             0.626224           12035.397508                    1
     GAS5             0.554820            2396.315699                    1
   MALAT1             0.503890            4113.415008                    1
     MIAT             0.462746             468.775911                    1
   SNHG12             0.408485             309.776139                    1
     XIST             0.316096            4477.996169                    1
LINC01116             0.268514               0.000000                    0
      H19             0.104000           16457.563256                    1
     MEG3             0.091500             628.060871                    1

In [42]:
from pathlib import Path

text = Path("app/dashboard.py").read_text()

chart_terms = [
    "st.bar_chart",
    "st.line_chart",
    "st.area_chart",
    "st.plotly_chart",
    "alt.Chart",
    "plotly",
]

for term in chart_terms:
    print(term, "->", term in text)

st.bar_chart -> False
st.line_chart -> False
st.area_chart -> False
st.plotly_chart -> False
alt.Chart -> False
plotly -> False

In [43]:
st.subheader("TCGA Pan-Cancer Expression")

plot_df = scored_df.copy()

needed_cols = {"symbol", "expr_mean_tcga_pancan", "translational_score"}
if needed_cols.issubset(plot_df.columns):
    plot_df = plot_df[list(needed_cols)].copy()
    plot_df["expr_mean_tcga_pancan"] = pd.to_numeric(
        plot_df["expr_mean_tcga_pancan"], errors="coerce"
    )
    plot_df = plot_df.dropna(subset=["expr_mean_tcga_pancan"])
    plot_df = plot_df[plot_df["expr_mean_tcga_pancan"] > 0]
    plot_df = plot_df.sort_values("expr_mean_tcga_pancan", ascending=False)

    if not plot_df.empty:
        st.bar_chart(plot_df.set_index("symbol")["expr_mean_tcga_pancan"])
    else:
        st.info("No non-zero TCGA pan-cancer expression values available to plot.")
else:
    st.info("TCGA pan-cancer expression data not available for plotting.")

NameError: name 'st' is not defined

In [44]:
st.subheader("TCGA Pan-Cancer Expression")

needed_cols = {"symbol", "expr_mean_tcga_pancan", "translational_score"}
if needed_cols.issubset(scored_df.columns):
    plot_df = scored_df[list(needed_cols)].copy()
    plot_df["expr_mean_tcga_pancan"] = pd.to_numeric(
        plot_df["expr_mean_tcga_pancan"], errors="coerce"
    )
    plot_df = plot_df.dropna(subset=["expr_mean_tcga_pancan"])
    plot_df = plot_df[plot_df["expr_mean_tcga_pancan"] > 0]
    plot_df = plot_df.sort_values("expr_mean_tcga_pancan", ascending=False)

    if not plot_df.empty:
        st.bar_chart(plot_df.set_index("symbol")["expr_mean_tcga_pancan"])
    else:
        st.info("No non-zero TCGA pan-cancer expression values available to plot.")
else:
    st.info("TCGA pan-cancer expression data not available for plotting.")

NameError: name 'st' is not defined

In [45]:
pwd
git status
git remote -v
git branch -vv
find . -name "health_check.py"
git ls-files | grep health_check.py
git log --oneline -5

SyntaxError: invalid syntax (2817622587.py, line 2)